### ISSUE TITLE
python3 compatibility?

### ISSUE THREAD

**Issue by sabernar** [locustio/locust#107]
Any chance that locust can be made python3 compatible?

**Comment by botchniaque** [comment]
Looks like gevent Python3 issue has just got resolved (13.07.2015). Does it get locust Python3 compatibility closer? Can you reopen this ticket?

**Comment by cgoldberg** [comment]
few comments:

I've ported many codebases from Python2->Python3.  I highly recommend keeping a single codebase that runs under 2 and 3, rather than maintaining a separate Python 3 port.

`six` is a great library that helps with compatibility and porting.  Highly recommended.

Also add `tox` for local testing across Python versions.

(just my $.02)

I'd love to see locust run under py3, and I can help porting where needed.

**Comment by paultiplady** [comment]
This was continued in https://github.com/locustio/locust/pull/363
