### ISSUE TITLE
Throughput (RPS) value is not same in Locust WEBUI and http://localhost:8089/stats/requests/csv for same number of requests

### ISSUE THREAD

**Issue by nityasantoshi** [locustio/locust#1108]

**Comment by cgoldberg** [comment]
Please fill out the template when submitting issues.

It is unclear what this actually means or when it occurs.

**Comment by nityasantoshi** [comment]
@cgoldberg, What I am saying is When I see the RPS on LOCUST UI is different from the When I am trying to get the report while LOCUST server is running via http://localhost:8089/stats/requests/csv. This URL generates CSV file for with the below metrics. Please find the screenshot for csv output.
<img width="551" alt="Screen Shot 2019-10-09 at 1 42 37 PM" src="https://user-images.githubusercontent.com/8496177/66506188-dc190080-ea9a-11e9-8827-ab137ee7662c.png">

**Comment by cgoldberg** [comment]
again.... **Please fill out the template when submitting issues.**

We have no idea what you are running, how you are running it, when this situation occurs, or how to reproduce it.  Rather than having me spend time guessing what might be happening, why don't you just fill out a proper issue report and give us the details that are requested in the issue template?
