### ISSUE TITLE
Installing 0.12.1 requires "pipenv lock --pre"

### ISSUE THREAD

**Issue by schinckel** [locustio/locust#1116]
The latest release of `locustio` cannot really be managed using pipenv. It includes a dependency of `geventhttpclient-wheels`, which has only pre-release versions available.

As such, it is not possible to generate a `Pipfile.lock` file without using `pipenv lock --pre`.

Doing this will install pre-release versions of other packages, which is problematic. (In my case, it installed a 5.0dev version of coverage, which uses a different coverage file format).

**Comment by schinckel** [comment]
(It's possible that this was also present in earlier versions: my last lock file that worked correctly indicated that it worked fine with 0.11.0).

**Comment by schinckel** [comment]
I’m not sure: I think maybe Pipenv would still complain.

**Comment by heyman** [comment]
I just tried installing geventhttpclient-wheels using pipenv:
```
pipenv install geventhttpclient-wheels
```
Which failed because I didn't use the `--pre` flag. However the installation succeeded when I ran:
```
pipenv install geventhttpclient-wheels==1.3.1.dev2
```
Wouldn't that indicate that it would work if we pinned the version locust's setup.py? I haven't used  pipenv much, and not sure how to test it.

**Comment by heyman** [comment]
I pinned the version in master, and now `pipenv install -e git+https://github.com/locustio/locust.git#egg=locustio` succeeds, so I'm assuming it fixed it.

**Comment by martinpeck** [comment]
I'm not sure this has fixed things. The version of gevent being specified for locust is 1.5a2. This is a pre-release version. When I `pipenv install locustio` I get the same errors as the original poster.

**Comment by easherma** [comment]
Same, I get the same errors. @heyman Can you re-open this?

**Comment by heyman** [comment]
That's unfortunate. I could issue a non pre-release version of the geventhttpclient-wheels package, though I'd prefer not to, since I think it'd be better to follow the same version number as the official geventhttpclient package.

Gevent 1.5 fixes fixes a bug which would cause Locust's Web UI to crash on Python 3.8 (#1154), so I don't think we'd want to downgrade to gevent 1.4 (the latest non pre-release version). 

Therefore, I don't see a good fix for this at the moment, except from maybe documenting it.

**Comment by cyberw** [comment]
@heyman You reopened this, but say there is no good solution :) I guess we are stuck waiting for a new release on geventhttpclient? Or should we "solve" the ticket by just documenting it?

**Comment by heyman** [comment]
@cyberw We currently also pin the gevent version to 1.5a2 (to fix a crash on Python 3.8 (#1154)) which also is a pre-release version, so just releasing a non pre-release version of geventhttpclient-wheels won't resolve it.

I think we should wait with a fix until gevent 1.5 is released. Until then I think it's a good idea to leave this open so that it's more discoverable for people running into the issue.

**Comment by linhnvhicts** [comment]
I encountered the same problem with locustio 0.4.5 version 

`Could not find a version that matches gevent==1.5a3,>=0.13`

Are there anyway to resolve this problem or loscustio just can't be installed with pipenv till 1.5 released ?

**Comment by farridav** [comment]
This has affected me too, used workaround thanks @linhnvhicts

**Comment by cyberw** [comment]
@heyman Now that there is a gevent 1.5 release, I guess we could build a non-prerelease eventhttpclient-wheels version?

**Comment by heyman** [comment]
@cyberw Yes, we could do that. Only problem is that the version numbers in our `geventhttpclient-wheels` package would diverge from `geventhttpclient`, but maybe that's okay.

**Comment by Kilo59** [comment]
@linhnvhicts 
@cyberw 

IMO using the pre-release flag is not a good solution, as it will cause ALL dependencies in your project to use the lastest `pre-release` versions, which are often time unstable and could cause things to break in unpredictable ways.

You are better of adding a pinned version of  `geventhttpclient-wheels` to your `Pipfile` as @heyman [suggested](https://github.com/locustio/locust/issues/1116#issuecomment-545156978).

`pipenv install geventhttpclient-wheels==1.3.1.dev3`

Also try clearing your `pipenv` cache and re-locking.
`pipenv lock --clear`
https://pipenv.pypa.io/en/latest/diagnose/#your-dependencies-could-not-be-resolved

**Comment by cyberw** [comment]
Fixed (a while back)
