### ISSUE TITLE
number locusts must be a multiple of the number of slaves

### ISSUE THREAD

**Issue by sanga** [locustio/locust#112]
We have 80 slaves in our set up and this is somewhat restrictive at times i.e. at times it would be nice step in finer jumps than 80 (of course I could kill some slaves, but that's a bit clunky)

**Comment by abhimanyuPlivo** [comment]
Is this issue still persisting?  I have 16 Slaves in my setup and have 30 different types of users defined. Seems like the minimum load I can run is with 16 * 30 = 480 locusts.

**Comment by wreed4** [comment]
This is definitely still an issue for me, but it doesn't seem as clear cut.  I was running with 10 slaves, 100 Locust classes in my locustfile (because I need to hit 100 different hosts) and the minimum number of users I can run with is 501.  500 or less spawns zero users.  It might also have to do with the spawn rate.
