### ISSUE TITLE
Automatically break and restart tasks on failure

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1124]
Many real world test cases have dependencies where subsequent request should/cant be executed if request has failed (bad return code, validation failure, whatever the issue). The locust default behaviour is to continue running the task.

Is there a way to do "restart task iteration on failure", without adding code after each request to "manually" restart iterations, by returning or raising an exception?

**Comment by heyman** [comment]
I would probably implement that functionality like something like this:
```python
from locust import HttpLocust, TaskSet, task, between
from locust.core import RescheduleTask

class UserTasks(TaskSet):
    def get(self, *args, **kwargs):
        response = self.client.get(*args, **kwargs)
        if response.ok:
            return response
        else:
            raise RescheduleTask()

    @task
    def page404(self):
        self.get("/does_not_exist")
```

That would require one to use the custom `self.get()` method for making GET requests instead of `self.client.get()`. I think that is a pretty good practice anyway, since it's quite common that you at some point realize that you want to do something for every request (e.g. add an HTTP header, basic auth, etc.)

If I wanted the task that failed to be retried I would do something like:
```python
from locust import HttpLocust, TaskSet, task, between
from locust.core import RescheduleTask

class RequestFailure(Exception): pass

class UserTasks(TaskSet):
    def get(self, *args, **kwargs):
        response = self.client.get(*args, **kwargs)
        if response.ok:
            return response
        else:
            raise RequestFailure()
    
    def execute_task(self, task, *args, **kwargs):
        try:
            super().execute_task(task, *args, **kwargs)
        except RequestFailure:
            self.schedule_task(task, args=args, kwargs=kwargs)
            raise RescheduleTask() 

    @task
    def page404(self):
        self.get("/does_not_exist")
```

I'm not sure if I think that the functionality should be built in though. If so, how should it work? Should it work like my first example example, or  like the second one (that the same task is retried)? Should it skip the wait timeand jut retry it immediately? (I think definitely not because it would cause the RPS/load to spike when getting close to the maximum load a system can handle and requests starts to fail).

**Comment by HeyHugo** [comment]
Havn't run this but maybe this could work. Using the `request_failure` event hook
```python
from locust.events import request_failure
from locust import InterruptTaskSet

def on_request_failure(request_type, name, response_time, exception):
    # Dispatch exception.response e.g check for specific status_code here
    raise InterruptTaskSet(reschedule=True)

request_failure += on_request_failure
```

**Comment by heyman** [comment]
@HeyHugo That could actually work, but would also have massive potential of breaking stuff, since it would prevent any request_failure event handler registered after `on_request_failure` to never run :).

**Comment by cyberw** [comment]
I think the functionality deserves to be built in because it is such a common use case (in some tools it is even the default behaviour). At the very least we should provide an example on how to do it.

My title was misleading: I dont want the particular task to be restarted, just to end that particular iteration and not do the subsequent requests. Whether we sleep or not could be up to the user (default should be yes, for the reasons you mentioned).

@HeyHugo Interesting... maybe something along those lines could work...

**Comment by heyman** [comment]
> I dont want the particular task to be restarted, just to end that particular iteration and not continue running (doing the remaining requests)

I see. Yeah, having the ability to make the task end immediately upon a request failure could make sense I think. 

Implementation wise I think we would raise an exception from within the HTTP client (and that we would handle within the TaskSet code):

https://github.com/locustio/locust/blob/d3a195deb59d2787490e1a598de08b35836c00bb/locust/clients.py#L133-L141

(not just re-raise the RequestException, since we want to provide the same functionality for custom clients)

**Comment by cyberw** [comment]
I did an ugly workaround in the plugins package. I should really do a proper fix though :) https://github.com/SvenskaSpel/locust-plugins/blob/master/examples/restart_on_fail.py

**Comment by jayqi** [comment]
For anyone else who tries to implement this, it seems like `RescheduleTask` got moved sometime in the last couple of years. The import should now be:

```python
from locust.exception import RescheduleTask
```
