### ISSUE TITLE
When the response time increases, the RPS decreases. How do we keep it stable

### ISSUE THREAD

**Issue by weinine333** [locustio/locust#1141]
When the response time increases, the RPS decreases. How do we keep RPS stable?

![q](https://user-images.githubusercontent.com/14816107/68649667-3146a700-055e-11ea-9275-37a409f27f62.jpg)

I setting 7 instance in aws ec2 class，
Run bellow command on each instance ：
locust -f  app.py -H https://webapi :5000

I find when the response time increases, the RPS decreases.
How do we keep RPS stable?

- OS: Ubuntu 14.04.6
- Python version: Python 2.7.6
- Locust version:  locustio 0.12.2(branches wait_time)

**Comment by heyman** [comment]
Since you're using the wait_time branch, you could use the `contant_pacing()` wait_time function: https://github.com/locustio/locust/blob/c3235457a394ec4cae260587b2b8f75967d24ef0/locust/wait_time.py#L39-L40

That would automatically decrease the wait time for the simulated users when the task execution time increases. However, that would only manage to keep the RPS level as long as the wait time is longer than the average task execution time. 

It would be hard to have 200 users manage to create a load of more than 200 RPS when you have an average response time of 1000 ms (unless you spawn threads/greenlets within your tasksets).

Why do you want to keep the RPS stable?

**Comment by weinine333** [comment]
thank you very much
