### ISSUE TITLE
Documentation on how to best configure a (linux) machine to run locust

### ISSUE THREAD

**Issue by heyman** [locustio/locust#128]
We should have a page in the documentation that describes how to set up an Ubuntu machine, and perhaps other popular linux dists, that is ready to run locust load tests.

Should cover how to install dependencies, up file descriptor limit, etc.

**Comment by ravitejagv92** [comment]
+1

**Comment by sylink** [comment]
This somewhat exists - http://docs.locust.io/en/latest/installation.html#increasing-maximum-number-of-open-files-limit

But you really just have to search the ulimit for your distribution, and there is no need to document that in Locust itself. Otherwise, throw CPU at it if you see it slowing down during testing, though it uses very few resources itself from my experience.
