### ISSUE TITLE
Persist charts

### ISSUE THREAD

**Issue by yashbhutwala** [locustio/locust#1294]
### Is your feature request related to a problem? Please describe.

Currently charts are not persisted across sessions.  Ability to export and download charts after a run would be super helpful!

**Comment by jheld** [comment]
So this probably would need to be stored on the server? If different users (browsers/computers) want to see.

As far as how data collection and propagation would occur the server would probably need an API to return the initial data, and one (maybe just extended query param) for time based deltas (points after a certain time or "page", essentially pagination).

I agree it would be nice to support this feature -- opt in possibly.

If we find doing it from the server is too much overhead, then yes, we could put this in local storage or something on the browser (with a UI button to clear/reset the charts).

How does this sound?

**Comment by heyman** [comment]
Locust will never be able to do as good job of visualizing stats as a proper time-series database and dedicated visualization tool. We've so far chosen to focus on the core user simulation/load testing functionality, and only include the extremely basic and ephemeral JS charts in the Web UI (for a long time Locust didn't have *any* charts), since it's fairly easy to make Locust post stats to some external tool (e.g. StatsD/Graphite/Grafana) specialised in visualizing stats.

If we were to implement server side charts we would have to think about where we would want to put the bar when it comes to functionality VS performance/memory usage VS codebase size, etc. I think it can be done, but it's not a quickfix.

**Comment by cyberw** [comment]
kind of fixed by the "full report download" feature implemented a while back. If that is not enough for you, have a look at TimescaleListener https://github.com/SvenskaSpel/locust-plugins#listeners
