### ISSUE TITLE
Run locust as a job but still have access to the API.

### ISSUE THREAD

**Issue by drPytho** [locustio/locust#1305]
### Is your feature request related to a problem? Please describe.
I want to be able to run locust as a job i.e. `locust -c 100 -r 10 --run-time 30m` and still have access to the stats API and custom endpoints. Right now it forces me to run it with `--no-web` which removes API access. 

### Describe the solution you'd like
Allow them to run together or partial versions of them. 

### Describe alternatives you've considered
Starting up a separate Flask server

**Comment by heyman** [comment]
The ability to run Locust programatically in 1.0 (under development in master) will make this possible with a few lines of code. 

We could also make this work straight from the command line, but in that case I don't think it's clear what we would want the behaviour to be once the `--run-time` duration has passed. E.g. would we want it to just stop the test while keeping the Locust process (and the Web UI) running, or would we want the process to stop (like `--run-time` currently works)? I can see merits for both. 

Also we would have to implement run time functionality within the Web UI or else things would get weird when user starts controlling the test from the WebUI  while `--run-time` is specified.

**Comment by drPytho** [comment]
Could we split the API and the static site serving? Or if we have `--no-web` we still lauch the API?

**Comment by Trouv** [comment]
This issue is similar to #1187

I'd also be interested in the ability to have an automatically started (and automatically stopped) test in web mode. Especially now that `-c, -r, --step-clients, and --step-time` automatically populate every field you need to set before starting a test in web-mode, it seems the next logical step would be to remove the need to click "start swarming" at all.

Two potential issues:
1. I could see somebody wanting to do this without specifying `--run-time`. 
2. I could see frustration with the fact that charts don't persist. Any visualization that happens at the start of the test before the user gets the chance to load the web-page will be lost

Maybe we could have a new option, like `--swarm-delay/-d`, which could double as a way to specify automatic start in web-mode, and to provide a delay to start the test in both web and headless mode. That way, a user can give a short delay in web mode to have the test start automatically but also give them a chance to load the page before the test starts.

However, there are two more issues I could see with this solution:
1. What happens to the startup page in web mode during the delay?
2. The name `--swarm-delay` doesn't really imply that it enables automatic starting in web-mode very well

Thoughts?

> would we want it to just stop the test while keeping the Locust process (and the Web UI) running, or would we want the process to stop (like `--run-time` currently works)? I can see merits for both.

I think it makes slightly more sense to stop the entire process. You won't be able to see the charts if you load the web-page after the test anyway, and the web-page mostly works fine after the process stops if you loaded it before. This way, if someone were to run the test as part of a larger script, and wanted access to the web-page/api during the test, their script wouldn't just hang after the test is over.

**Comment by heyman** [comment]
> Maybe we could have a new option, like --swarm-delay/-d, which could double as a way to specify automatic start in web-mode, and to provide a delay to start the test in both web and headless mode.

I not very fond of adding an extra command line option for this. It doesn't seem like a common enough use-case.

**Comment by cyberw** [comment]
I think @heyman s last comment is a good solution for this.
