### ISSUE TITLE
Graph capabilities export in no web UI mode (CLI) 

### ISSUE THREAD

**Issue by jayeshd7** [locustio/locust#1321]
### Is your feature request related to a problem? Please describe.
I am running my Load TC on Docker and it is in CLI mode .
I am okay with CSV report which i am storing in one folder , which I am published Jenkins as well.

For some better understanding if I can get or export graph as well in CLI mode.
it is very good to see when we open our jobs in jenkins and finding there all results in graph format.

**Comment by heyman** [comment]
Your current options are to either create your own graphs from the data in the CSV history file (if that is enough), or shoot the stats to some external graphing solution (for example Grafana).

**Comment by Trouv** [comment]
It might be nice to have a `--web-display` or `--web-load` or just `--load` flag which would put up a webpage displaying some old results that you provide the csvs for. You could use the `--csv/--csv-base-name` flag for this, or maybe just have `--load` accept a basename in a similar way. The `--web-host, --web-port, and --web-auth` options could work here too. The webpage would exclude things like the 'new swarm' prompt and the stop/new test buttons.

This would mean that you could get some basic visualization when you use locust in cli mode (especially useful for those who've automated their locust usage), and you could share these visualizations with other devs by sharing the csvs instead of downloading the chart pngs.

It sounds like a lot of work but it could be useful for some folks

**Comment by Trouv** [comment]
This may also help relieve any frustration with the fact that charts don't persist #1294

**Comment by heyman** [comment]
> This would mean that you could get some basic visualization when you use locust in cli mode (especially useful for those who've automated their locust usage), and you could share these visualizations with other devs by sharing the csvs instead of downloading the chart pngs.
>
> It sounds like a lot of work but it could be useful for some folks

It sounds like it could be useful sometimes, though I think it would be better as a separate project rather than a feature built into Locust. Not much of the existing Locust code could be re-used for this anyways (since the internal classes used within Locust to generate the Web UI has a different structure and contains more data than the CSV files).

**Comment by cyberw** [comment]
There are some solutions for displaying the output in Grafana:
Using Timescale (each sample logged, made by me :) https://github.com/SvenskaSpel/locust-plugins
Using Graphite (aggregated data, I cant vouch for how well it works) https://gist.github.com/lucindo/1f7739cdc9187b54d84e
