### ISSUE TITLE
"Order of events" clarification

### ISSUE THREAD

**Issue by ecc256** [locustio/locust#1349]
Guys,
Question / clarification about [Locust setup (once)](https://docs.locust.io/en/stable/writing-a-locustfile.html#order-of-events)
Indeed, it’s called once only, for very 1st HttpLocust **instance**.

I've set an **instance** attribute in `setup(self)` is **instance** method.
Consequently, only 1st HttpLocust **instance** has the attribute set.
All others HttpLocust **instances** won’t have the attribute and throw an exception on access.

Naturally, setting **class** attribute instead will take care of it.

A thought:
Since Locust setup() is called once only, should it be **class** method, not **instance** one?
Would be nice to add Locust on_start (once per locust) **instance** method too, seems a bit more logical to me...

Above applies to TaskSet too:
TaskSet setup (once) - should be **class** method, not **instance**
TaskSet on_start (once per locust) - is **instance** method

Not complaining or anything, just want to throw an idea!
Thanks

**Comment by cyberw** [comment]
Hi! You are totally right! It is very confusing! It is fixed in the upcoming (as in any day now) 1.0 release though :)

If you want to try it out right away, try installing locust from latest master (`pip3 install -e git://github.com/locustio/locust.git@master#egg=locustio`) and check out the documentation here https://docs.locust.io/en/latest/writing-a-locustfile.html#setups-teardowns-on-start-and-on-stop

**Comment by ecc256** [comment]
Would love to test!!
Ugh... I don't see "setups-teardowns-on-start-and-on-stop" section in the link you posted...

**Comment by ecc256** [comment]
Tested latest branch - works great!
Thanks a lot for your work!
And for switching to newer **gevent** too! 
`gevent                    1.5.0                    pypi_0    pypi`
