### ISSUE TITLE
Let hatch rate be provided by a callable

### ISSUE THREAD

**Issue by steodorescu** [locustio/locust#1353]
I want to emulate loads that represent user activity based on a specific distribution.

Let' say the users have to login every morning. Some login around 8am, some login around 10am, most of them login around 9am.
It would be nice to tell locust to vary the client hatch rate following a statistical distribution of sorts over a given interval.

**Comment by heldic** [comment]
I'd appreciate the same feature. In case you're not aware, you can opt to approximate a desired behaviour by shooting a bunch of POST requests to `/swarm` until predefined patterns/distributions are supported.

Regarding the desired feature: You might want to check out those two comments (and issues #1001 & #1002):
- https://github.com/locustio/locust/issues/1001#issuecomment-541416770
- https://github.com/locustio/locust/issues/1001#issuecomment-546004337

They suggest that such a feature might already be on the radar of @heyman, at least he's 
also mentioned something related to this again in PR #1266:
> Here are other changes that I think we should implement/consider for a 1.0. Most of them have been suggested/requested by others before at some point:
[...]
> - [ ] Re-work the step load feature. I'd like it to be something more general like a run plan with an API that one can hook into. It should also be able to both spawn and kill simulated users.

However, since there appears to be no open issue for this feature request anymore, maybe this is a good starting point.

**Comment by cyberw** [comment]
Another way to work around it might be to do a sleep-loop until your specified time. Or use a cron job to start a completely new run of locust at a given time. I dont think we'll build this any time soon...

**Comment by cyberw** [comment]
(reopen with low prio, now that we use that label)

**Comment by cyberw** [comment]
Superseeded by load shape feature
