### ISSUE TITLE
stop-timeout option is not working. Tests are stopped immediately after configured run time.

### ISSUE THREAD

**Issue by rohithkumar31** [locustio/locust#1393]
### Describe the bug
Tried running locust test with runtime '6 hours' and stop time '10 hours' in seconds. I needed extra stop time because I had to do s3 cleanup as part of my test. But the locust runner stops immediately after 6 hours. The stop time is not considered.

### Expected behavior
The stop time should be respected and the currently running tasks should be allowed continue to completion

### Actual behavior
Test is abruptly killed after configured runtime

### Steps to reproduce
 
1. Created a locust test 
2. Triggered the test for 6 hours with options (-t 6h -s 36000 )
### Environment

- OS: Ubuntu
- Python version: 3.8
- Locust version: 1.0.1
- Locust command line that you ran: locust -f locustfile.py -u 100 -r 1 -t 6h -s 36000

**Comment by cyberw** [comment]
Need more details. I think it works in general but maybe there is some special case I have not considered.

**Comment by heyman** [comment]
Note that a user that is currently "waiting" is not considered as currently running. Locust will only wait for users that are currently executing a task. 

Don't know if that might be the issue here, but putting this here just in case. If not, more details are needed just as @cyberw says. A minimal reproducible example would be perfect.
