### ISSUE TITLE
Support Needed- How to clear cache after a test run or close the session

### ISSUE THREAD

**Issue by Dhams-1** [locustio/locust#1429]
HI,
I am new to Locust. I have a question. I am performing a post action with a locust test and that returns me a response time  Max  value as 50 seconds and Average value as 10 seconds. When i run the same test again i get the response time for Max, Min and Average as 10 seconds.  I somehow feel that it is happening because of caching or because the session is not closed and i am not sure how to solve the same. it would be really helpful if some one can support me here. Here is the sample post request code.

 @task
    def sample_task(self):
        res3 = self.client.post("/ur/to/post",
                                headers=request_headers,
                                data=sample_data,
                                cookies=cookies_input)

**Comment by cyberw** [comment]
Hi! There is no cache in locust, the faster response times after repeated tests must be because of caching/some other improvement on the server side.

The session is not closed between requests, but I doubt that is the cause of the discrepancy. If you do want to clear cookies/session you can do it like this: https://stackoverflow.com/questions/62285789/how-to-clear-cookies-at-end-of-locust-io-user-workflow/62290527#62290527

The http connection is not closed between iterations either, but I dont think that is your "problem" either (if there really is a problem)

For further questions, please use stackoverflow.
