### ISSUE TITLE
Number of http request is greater than number of user given in UI

### ISSUE THREAD

**Issue by pankaj-kaushik** [locustio/locust#1433]
Hi,

In locust statistics, i can see that aggregated HTTP request is more than the number of user provided in UI.

Ideally http request should be equal to number of user entered in UI.

**Comment by cyberw** [comment]
Every user loops after completing its tasks

**Comment by pankaj-kaushik** [comment]
@cyberw : It is not clearly documented in the docs and how to stop the iterations. Can you please let me know, what should i do to make aggregated request equal to amount of user.

**Comment by heyman** [comment]
@pankaj-kaushik That's not possible in a clean way since it doesn't fit well with how Locust works. There are various work-arounds that one could implement within the test script code to achieve a similar behaviour (with different limitations depending on if the tests are ran distributed or not), though I'd recommend against it since one would be using Locust in a way that's pretty far from the intended one.

**Comment by pankaj-kaushik** [comment]
@heyman : thanks for your response. Actually i am facing below challenges. I would really appreciate if you can guide me on following.

**Challenges**
1. Loadgen CPU Utilization is reaching to 90%.
2. Number of HTTP request is always greater than number of users configured in UI. I would like to make it equal. Below is my locust file.

**Environment Used**
1. 2vCPU and 2 GB RAM
2. One Locust Master and 3 Locust Slave on AWS EC2.

My Sample Locust File.

`import random
from locust import HttpUser, task, between

class QuickstartUser(HttpUser):
    wait_time = between(1, 2)

    @task
    def index_page(self):
        self.client.get("/")`
