### ISSUE TITLE
Can't extend docker image with pip3 install <any-package>

### ISSUE THREAD

**Issue by lhenry7** [locustio/locust#1451]
See https://github.com/pypa/pypi-support/issues/467

### Describe the bug
pip3 install does not work, see linked issue and gist

### Environment

- OS:
- Python version:
- Locust version:
- Locust command line that you ran:
- Locust file contents (anonymized if necessary):

**Comment by cyberw** [comment]
Isnt this an issue with pip or the base image? Why double post the issue?

**Comment by lhenry7** [comment]
Yes I think that is where the issue is, double posted just in case anyone here has any insight or has already dealt with the issue. I've gotten no response on the pypi issue.

**Comment by cyberw** [comment]
I think you may have a network issue. Works fine for me at least!

lafp@mac:~ docker run -it --entrypoint /bin/sh locustio/locust
/ $ pip3 install pymongo
Defaulting to user installation because normal site-packages is not writeable
Collecting pymongo
  Downloading pymongo-3.10.1.tar.gz (715 kB)
     |████████████████████████████████| 715 kB 2.2 MB/s
Building wheels for collected packages: pymongo
  Building wheel for pymongo (setup.py) ... done
  Created wheel for pymongo: filename=pymongo-3.10.1-cp38-cp38-linux_x86_64.whl size=315900 sha256=a7c10c961dfd3e08542e1a740f2fda1b8c6a39ab345fe702a0561bc14e0bbeff
  Stored in directory: /home/locust/.cache/pip/wheels/2b/1a/60/fcd298c7a5be7dc85993c8e92bc9aebec88b0d56fd7d9d134c
Successfully built pymongo
Installing collected packages: pymongo
Successfully installed pymongo-3.10.1
