### ISSUE TITLE
how rps works and how to increase it

### ISSUE THREAD

**Issue by acorrea-B** [locustio/locust#1497]
we were doing some load tests to an API we put the wait time between 1 and 3 and we put Number of total users to simulate in 200 the Hatch rate from three different machines at the same time, the rps in the three machines remains between 7 and 10 which was the one with the highest value as can be seen in the attached image one of the samples, but we do not understand for sure why it happens or we would like to have more information about it thanks.
![total_requests_per_second_1596065142](https://user-images.githubusercontent.com/63741555/88947510-3cf60d00-d256-11ea-8493-8101c08ffe0c.png)

**Comment by cyberw** [comment]
Hi! I’ve been thinking about writing something about this, as ”why is my rps so low” is a common question. Does any of this help?

1. Increase the number of users. In order to fully utilize your target system you may need a lot of simultaneous users.

2. If response times are unexpectedly high and/or increasing as the number of users go up, then you have probably saturated the system you are testing and need to dig into why. This is not really a Locust problem, but here are some things you may want to check:
- resource utilization (e.g. CPU, memory) 
- configuration (e.g. max threads for your web server) 
- back end response times (e.g. DB)

3. If Locust is complaining about high CPU usage on its side
- Run Locust distributed to utilize multiple cores & multiple machines
- Try switching to FastHttpUser

**Comment by acorrea-B** [comment]
thanks for your help, so then the rps is not exactly proportional to the number of users per second, but to the different variables that are presented in the test such as the system being tested or the handling of the processor, etc.

questions to which we must consider when carrying out the tests or during these parameters that must be adjusted as progress is made in them.

right?

**Comment by cyberw** [comment]
Yes. In theory, RPS will be: number of users/(response time + sleep time)

So if your system under test starts to slow down your RPS will fall.

**Comment by acorrea-B** [comment]
ooo thank you very much @cyberw, for your help.
