### ISSUE TITLE
Stop load test after one iteration

### ISSUE THREAD

**Issue by Zeltserj** [locustio/locust#1499]
Hi,
I want to implement a "load test sanity check" so when my team commits new code it doesn't break the load testing logic.
So I have a set of simple tasks that I want one user to preform and then quit. But there is no "quit after all tasks were done once" feature! This sanity check will be put in a Docker image and later scaled, so it makes sense to use locust to make sure the whole pipeline works. I can only use `--run-time` but I do not want to commit to a certain runtime.

**Comment by heyman** [comment]
There's no built in way for making each task run exactly once. My first recommendation would be to pick a number of simulated users and a run time that would make it very likely that all your tasks would be executed at least once. 

An alternative approach - which is a bit more complex, but should for some use-cases - could be to group tasks under `SequentialTaskSets` as well as set the wait time to really low, if some environment variable is set. Here's an example:

```python
import os
from locust import User, SequentialTaskSet, TaskSet, task, constant, between
from locust.exception import RescheduleTaskImmediately

if os.environ.get("TEST_MODE"):
    BaseTaskSet = SequentialTaskSet
    wait_time_func = constant(0)
else:
    BaseTaskSet = TaskSet
    wait_time_func = between(1, 4)

class MyTasks(BaseTaskSet):
    @task
    def my_task(self):
        print("my_task")
    
    @task
    def seconds_task(self):
        print("second_task")
    
    @task
    def halt(self):
        if os.environ.get("TEST_MODE"):
            self.user.environment.runner.quit()
        else:
            raise RescheduleTaskImmediately()

class MyUser(User):
    tasks = [MyTasks]
    wait_time = wait_time_func

```

One caveat with the above solution when using nested TaskSets, is that it would only work as desired when only a single task (per TaskSet) calls `self.interrupt()`, and that task would have to be the last one, since [interrupt()](https://docs.locust.io/en/stable/writing-a-locustfile.html#interrupting-a-taskset) will cause execution to return to the parent TaskSet/User.

**Comment by Zeltserj** [comment]
This helped! thank you. I did modify it, because ` raise RescheduleTaskImmediately()` did not work as I intended. instead the whole `halt` function is in the `os.environ` condition

**Comment by drvgao** [comment]
Hi @Zeltserj,
Could you please post the final working solution? I'm having a similar problem. Thank you!

**Comment by mathe-matician** [comment]
@heyman it seems a bit strange to me to not stop the load test once all tasks are completed or have a better option than using TaskSets / `run-time`. Can you help me understand what the lift would be to add this to locust? Or if something has been introduced since this issue was created that would allow me to do this?

@cyberw 
I did try using `environment.runner.quit()`, but it only seemed to work with 1 user. Testing this with 2 users, I call `environment.runner.quit()` in the on_stop of my user, but it ends up stopping both of my users. E.g. whichever user completes their task first ends the test for all users. Shouldn't each user get a runner? Maybe I'm just misunderstanding or their is a bug in my code.

**Comment by cyberw** [comment]
> @cyberw I did try using `environment.runner.quit()`, but it only seemed to work with 1 user. Testing this with 2 users, I call `environment.runner.quit()` in the on_stop of my user, but it ends up stopping both of my users. E.g. whichever user completes their task first ends the test for all users. 

Yea that is "as designed".

> Shouldn't each user get a runner? Maybe I'm just misunderstanding or their is a bug in my code.

No, a Runner is the thing running the users, responsible for starting/stopping them etc. There is only one runner instance (one per process when running distributed).

> To clarify, if I start my test with a single user in headless mode. When a certain condition happens, I call `raise StopUser()` on my user. I see `on_stop()` called. But `@events.test_stop.add_listener` is never called and the test just continues to print stats to stdout even though no users are running. EDIT: I guess this makes sense since the default behavior is just to run forever when no `run-time` is specified.

Dont raise StopUser, it is for internal purposes only. What you're looking for isnt really supported. A simple workaround might be just adding a really long sleep.

**Comment by mathe-matician** [comment]
I appreciate the quick response @cyberw! I can confirm the use of `raise StopUser()` was causing some unintended behavior with my load tests. I ultimately modified my code removing it and then used the iterations option from the [locust-plugins](https://github.com/SvenskaSpel/locust-plugins#command-line-options) - this solved my problem.

**Comment by tajogii** [comment]
@mathe-matician Hi, 
Could you please post the final working solution? I'm having a similar problem. Thank you!

**Comment by mathe-matician** [comment]
@tajogii I don't have a particular code example that I can share, but what it boiled down to for me is:

1. In my locust `task` I removed any direct use of `raise StopUser()` that I had when a failure or undesired state occurred
2. Installed the [locust-plugins](https://github.com/SvenskaSpel/locust-plugins?tab=readme-ov-file#command-line-options) library and when running the load test, pass in the flag `-i <number of iterations to run>` or `--iterations <number of iterations to run>`. If I wanted it to stop after 1 iteration, then I would pass in `--iterations 1`.

**Comment by nmhungdev** [comment]
@mathe-matician 
Do you know how to stop the test after reaching a certain number of iterations?

**Comment by cgoldberg** [comment]
@nmhungdev 

It was explained in the previous comment. Install `locust-plugins`, then use the `-i` parameter when starting locust to specify number of iterations.

**Comment by nmhungdev** [comment]
@cgoldberg 
I understand that, but it is not working properly.
Here is more detail: https://github.com/locustio/locust/issues/1085#issuecomment-2690049382

**Comment by cgoldberg** [comment]
@nmhungdev 

If it doesn't work, you should open a new issue in `locust-plugins` repo.
