### ISSUE TITLE
independent LoadTestShapes for users

### ISSUE THREAD

**Issue by stanislawskwark** [locustio/locust#1583]
### Describe the solution you'd like
I have a locustfile with 2 users and I would like to have independent LoadTestShapes for them. 
Some examples of usage:
constant number of users A and number of users B changing over time
initially big number of users A and small number of users B, and opposite at the end of test
more types of users with independent shapes

### Describe alternatives you've considered
I've been thinking about adjusting weights dynamically, but didn't really come up with any nice solution

### Additional context
example of shape I would like to get:
![image](https://user-images.githubusercontent.com/46684704/95177482-84e96100-07be-11eb-8969-08126e9ad9c3.png)

**Comment by cyberw** [comment]
Makes sense. If it can be done without complicating things too much, I think it is a good idea.

**Comment by stanislawskwark** [comment]
@max-rocket-internet I've seen you are the one who implemented LoadTestShapes functionality, could you guide me a little in this topic? I don't have any experience with development of locust

**Comment by max-rocket-internet** [comment]
Hi @stanislawskwark, the `LoadTestShape` class is manipulating the user count during a test on the master. This user count is kind of "global", not per `HttpUser`. I've not touched any of the `HttpUser` or weights code so can't really say how it could be implemented but I think not in the same way as `LoadTestShape`. Sorry I can't offer you any help here 🙂

**Comment by aek** [comment]
Maybe this could be done like the TaskSet nested class or tasks class member with a (list/set/dict) of task/tasksets

Something like this:
```python
class CustomShape1(LoadTestShape):
    def tick(self):
        pass

class CustomUser1(HttpUser):
    shape = CustomShape1

class CustomUser2(HttpUser):
    @shape
    class CustomShape2(LoadTestShape):
        def tick(self):
            pass
```
To use that design, the method `shape_worker` should be modified in order to look at the environment user_classes to retrieve custom user shapes to spawn different user count at different spawn_rate. All of this specified at the User level.
I think this could be a good fine grained way to manage user distributions where all the Users should be spawned at least once. 

Related to:
#1618 
#1635
#1621

**Comment by suiluj** [comment]
Are there any plans on this feature? I just started with locust and look for a solution to define different custom load shapes for different users.
