### ISSUE TITLE
Move the kubernetes helm chart stable/locust to this repo

### ISSUE THREAD

**Issue by nickhalden** [locustio/locust#1594]
Hi guys,
If you guys would like to move over a helm chart for locust in your repo i would like to contribute.
https://github.com/helm/charts/tree/master/stable/locust

https://github.com/helm/charts/issues/21103

Additionally, I will fix the chart for newer version as part of this migration.
https://github.com/helm/charts/issues/23905

**Comment by max-rocket-internet** [comment]
Hey @nickhalden,
I don't think it makes much sense putting helm charts into git repos that are not backed by a Helm repo because otherwise a user has to checkout the git repo to install the chart locally from the filesystem, which is a pain.

If you're a maintainer of the locust chart in old helm repo and you want to find a new home then I suggest updating the chart and committing it to [bitnami](https://github.com/bitnami/charts).

If you're not a maintainer of that chart and just want a chart to use, then I suggest you just use this chart, it's more up to date and documented: https://github.com/deliveryhero/helm-charts/tree/master/stable/locust
