### ISSUE TITLE
Creating a Customized Stats Report by Exposing a `summary_stats` object? 

### ISSUE THREAD

**Issue by RishabhMalviya** [locustio/locust#1613]
### Is your feature request related to a problem? Please describe.
I would like to export the summary results from Locust (headless) in a customized format.

### Describe the solution you'd like
I think we should create some way to access a `summary_stats` object at the end of the run, so that a user can work with it to create a report in whatever way he/she wants.

### Additional context
For example, I would like to get an output CSV that looks like this (could be more complicated):

![Capture](https://user-images.githubusercontent.com/6564529/97892989-bbcb7c00-1d56-11eb-8f4e-bf750954a3b0.PNG)

**Comment by cyberw** [comment]
Sounds useful. I guess we should add an event hook for it. Not going to do it myself though :)

**Comment by RishabhMalviya** [comment]
I'd be happy to work on it. I'm assuming the event hook is something that works at the greenlet (thread) level?

**Comment by cyberw** [comment]
Hi! Here is an introduction to the existing events: https://docs.locust.io/en/stable/extending-locust.html

You might be able to add summary_stats as a named parameter to the test_stop event (called at https://github.com/locustio/locust/blob/d9fea47deb7337c951b07aaa632b3a42dcb174e9/locust/runners.py#L409 https://github.com/locustio/locust/blob/d9fea47deb7337c951b07aaa632b3a42dcb174e9/locust/runners.py#L574 and https://github.com/locustio/locust/blob/d9fea47deb7337c951b07aaa632b3a42dcb174e9/locust/runners.py#L581)

**Comment by heyman** [comment]
The [stats](https://github.com/locustio/locust/blob/ab7201459f050d70e301fe5a4481f8dd227e2f61/locust/stats.py#L96) are already available through `Environment.stats`, and the `Environment` instance is passed to the `test_stop` event suggested by @cyberw. 

A `summary_stats` object would probably just end up holding the same data that the [RequestStats](https://github.com/locustio/locust/blob/ab7201459f050d70e301fe5a4481f8dd227e2f61/locust/stats.py#L96) class already holds. 

What would be great though would be to write documentation for the `RequestStats` and `StatsEntry` classes, and make them part of the public API. We would want to go through them and decide which of their members should be public, and make sure we use a consistent naming, etc. (since once we make the part of the public API, changing them would be a breaking change).

**Comment by RishabhMalviya** [comment]
So guys, I've been super busy and couldn't get back to this.

Based on what you explained @heyman, I think it will take some discussion to decide:
1. Which members of `RequestStats` and `StatsEntry` should be made public
2. And whether or not any renaming is required. 

In the meantime, can I write up the documentation for what is present in the classes right now (I can keep it in a separate branch and then incorporate changes based on what you decide)?

**Comment by KeyZJ** [comment]
Hello!
Any updates on it? Is it even possible to add custom (or manually control) request statistic in env.stats?
