### ISSUE TITLE
Locust is sending empty content

### ISSUE THREAD

**Issue by alterEgo123** [locustio/locust#1640]
### Describe the bug
I'm trying to upload a file to my Tornado web server using Locust. I've tried sending the HTTP request successfully using Postman and python's requests, but using Locust it is sending an empty content to the web server.

### Expected behavior
Sending the file (form data) to the web server.

### Actual behavior
Locust is sending an empty content

### Environment

- OS: Linux 18.04
- Python version: 3.6.9
- Locust version: 1.4.1
- Locust command line that you ran: locust -f locustfile.py
- Locust file contents (anonymized if necessary):

Trying the upload using python's requests:

```
import requests
url = "http://localhost:xxxxxxxxxxxxxxx/image_upload"
headers = {'Authorization': 'bearer xxxxxxxxxxxxxxxxxx'}
image = '/home/xxxx.jpeg'
files = {'file': open(image, 'rb')}
requests.post(url, files=files, headers=headers, verify=False)
```

Task inside locustfile:
```

@task(1)
def post_image(self):
    url = 'image_upload'
    image ='/home/xxxx.jpeg'
    files = {'file': open(image, 'rb')}
    headers = {'Authorization': 'bearer xxxxxxxxxxxxxxxxxx'}
    self.client.post(url, files=files,
                     headers=headers, verify=False
                     )
```

**Comment by aek** [comment]
@alterEgo123 Could you provide more information about the Locust User Client type?
I think that this could be happening with the FastHttpUser because I don't see an implementation of how to use the files argument with the geventhttpclient
Could @cyberw or @heyman confirm that this could be True?

**Comment by heyman** [comment]
@aek Yes, that sounds likely. This should be fixed/added to geventhttpclient.

**Comment by aek** [comment]
Perhaps we could provide a way to do it directly in the Locust FastHttpSession request?
I also notice that cookies aren't been used neither as reported [here](https://stackoverflow.com/questions/65217160/how-to-configure-or-set-cookie-as-json-before-making-a-post-request-in-locust-lo/65251359#65251359)
I was about to make a PR with the solution of that

**Comment by heyman** [comment]
Yes, another option is to implement it in Locust isntead. However, since I think it would improve geventhttpclient to push it's API more towards requests, I think it would be even better to implement it there. I suspect it might also might be simpler to do it there. We also have commit/release access to geventhttpclient.

**Comment by alterEgo123** [comment]
@aek I have tried this on both HttpUser and FastHttpUser

**Comment by aek** [comment]
You should be able to do it ok with the HttpUser since it use requests. Maybe you need to debug it, but it should work the same with HttpUser like directly with requests. 
I have created the following tests:
Directly with requests: https://hookbin.com/pzyQjNZqzmFXNNqwaWOn
<img width="810" alt="image" src="https://user-images.githubusercontent.com/404966/102096897-37f3bd80-3df3-11eb-9092-6b36aaa95185.png">

With Locust HttpUser and custom User Agent: https://hookbin.com/7ZzlOpDj1Pca99D3Rlkd
<img width="811" alt="image" src="https://user-images.githubusercontent.com/404966/102098289-04199780-3df5-11eb-817f-95de5cd06149.png">

With Locust FastHttpUser doesn't show anything as it send empty body and I get a 403 response from the hookbin endpoint test

**Comment by aek** [comment]
@heyman another idea it's to have the HttpUser class been able to use the client that it needs without using only one in the client property. Of course you could always do it by yourself, but it will be useful if you could access to all available clients integration directly from `self` and already setted up. [Zato ESB](https://zato.io/) uses this approach to provide Zato Services with it's integrations

**Comment by alterEgo123** [comment]
@aek Which version of Locust did you use?

**Comment by aek** [comment]
@alterEgo123 

**Environment**
    OS: macOS Big Sur 11.1
    Python version: 3.7.9
    Locust version: 1.4.1 (code from git master)
