### ISSUE TITLE
FR for configuration summary on locust page; happy to implement if reasonable

### ISSUE THREAD

**Issue by egnor** [locustio/locust#1642]
### Is your feature request related to a problem? Please describe.
Load tests have various configuration options (which test file, which test classes) which can be set on the command line but are not echoed in the status page. This can lead to some confusion (if you're not running the test you thought you were) and can make it a little harder to interpret screen grabs or reports.

### Describe the solution you'd like
It would be great if key configuration options (locustfile selected, weighted mixture of test classes, etc) would be shown in locust reports. (The host and current worker count are already shown which is great.)

### Describe alternatives you've considered
Can manage it by hand, but it's error prone!

### Additional context
I'm happy to make a PR if the feature seems reasonable.

**Comment by heyman** [comment]
I think it sounds reasonable!

If we're adding it to the Web UI (not just HTML reports), I don't think we should cram in more stuff into the top bar. Instead we could maybe add an additional tab (among the Statistics, Charts, Failures, etc.) where we could have this info.

If you want to give this a shot, I'd recommend you to base it on PR #1644 (since it brings quite a few changes to the Web UI/reports).
