### ISSUE TITLE
minor refactorings of User class

### ISSUE THREAD

**Issue by cyberw** [locustio/locust#1648]
* `start()` is always called immediately after construction (https://github.com/locustio/locust/blob/fasthttp-query-params/locust/runners.py#L197) so we can start the user in `__init__` & remove the start method. 

* Some variables are defined on the class level when they should only be defined on instance level / `__init__` (environment, state, etc). This introduces a lot of duplication, but most importantly becomes confusing to our users, as it is unclear what they can/should set on class level (host, abstract, etc) and what only exists on instance level (e.g. client)

Sound good to you @heyman ?

**Comment by heyman** [comment]
I think it still makes sense to keep the explicit call to `.start()`, even if it's currently always called directly after instantiation (outside the tests). It's not part of Locust's public API, and I think it makes the intent of the code more clear. Otherwise we'll get the side effect of spawning a greenlet when a User instance is created. The `start()` method is also symmetrical to the `stop()` method.

> Some variables are defined on the class level when they should only be defined on instance level / __init__ (environment, state, etc)

Hmm, in many cases we use the attributes on the class level for documentation. Both to refer to the attribute in the documentation text (example: https://github.com/locustio/locust/blame/afea8c0/docs/writing-a-locustfile.rst#L315), and for the API documentation. But maybe there's a better way to do the docstrings so that we can avoid unnecessary class level attributes?

**Comment by cyberw** [comment]
Symmetry is nice, but the User object is incomplete before .start is called which I feel is kind of bad.

It is kind of part of the public api, because every new User type needs to implement it, and confusing to whoever makes a new User because it makes it look like the methods will not be called in direct succession.

> Hmm, in many cases we use the attributes on the class level for documentation. Both to refer to the attribute in the documentation text (example: https://github.com/locustio/locust/blame/afea8c0/docs/writing-a-locustfile.rst#L315), and for the API documentation. But maybe there's a better way to do the docstrings so that we can avoid unnecessary class level attributes?

Agreed, we'll want to ensure the documentation still works. I remember looking at it a while back, and maybe I didnt find a solution, but I think there should be a way. I can have a look at it some time...

**Comment by heyman** [comment]
> Symmetry is nice, but the User object is incomplete before .start is called which I feel is kind of bad.

I'm not sure I understand what you mean by "incomplete". The `__init__` constructor creates a complete User instance. The `start()` method spawns a greenlet (in the supplied greenlet Group) and starts running the user loop.

As an example, imagine I'm writing a custom `User` class for some custom client and I want to write tests for it. Then I'd like to be able to do something like this:

```python
def test_user_has_client(self):
    user = CustomUser(create_environment())
    self.assertTrue(isinstance(user.custom_client, CustomClient))

def test_client_request(self):
    user = CustomUser(create_environment())
    user.client.request("resource_name")
    # assert request was made
```

Most of all I think it just makes the intent of the code more clear, having an explicit method that spawns a greenlet thread instead of automatically spawning it in the constructor.

> because every new User type needs to implement it

You only need to implement it if you want to overload the one from `User`, right?

> Agreed, we'll want to ensure the documentation still works. I remember looking at it a while back, and maybe I didnt find a solution, but I think there should be a way. I can have a look at it some time

:+1: If we can find a way to solve the documentation issue I'm all for it!
