### ISSUE TITLE
Cannot install locustio on nixos machine in nix-shell environment.

### ISSUE THREAD

**Issue by MajesticMullet** [locustio/locust#1663]
### Describe the bug
Cannot use locustio as when installing in a `nix-shell` as it does not pass its own tests. 

### Expected behavior
I expect locustio to be installed so I can use it. (Note that it is a part of [nixpkgs](https://search.nixos.org/packages?channel=20.09&show=python37Packages.locustio&from=0&size=30&sort=relevance&query=locust))

### Actual behavior
During installation, locustio fails on 3 of it's own tests. (74 pass).
![image](https://user-images.githubusercontent.com/31056089/102446428-dbf29880-4081-11eb-8bcc-dce05ed48ce0.png)

### Steps to reproduce
In your `default.nix` file have: 
```
{ buildPythonPackage
, nix-gitignore
, locustio
}:

buildPythonPackage {
 pname = "anything"
 version = "0.0.1"
 src = nix-gitignore.gitignoreSource [] ./.;
 propagatedBuildInputs = [
  locustio
 ];
}
```

### Environment

- OS: Nixos 20.09
- Python version: Python37
- Locustio version: 0.9.0

**Comment by cyberw** [comment]
Please update to latest.

**Comment by abathur** [comment]
@MajesticMullet This is more of an issue for https://github.com/nixos/nixpkgs. FWIW, though, locust has been recently removed from nixpkgs due to a lack of interest/maintenance (nixos/nixpkgs#104351), so you may want to spend a little time extolling its virtues on the nixpkgs tracker or discourse if it is something you need.
