### ISSUE TITLE
Feature request: Stepped hatch rate

### ISSUE THREAD

**Issue by MattFisher** [locustio/locust#168]
With a constantly increasing load due to a constant hatch rate, the server doesn't have time to steady-state and produce stable statistics.

I would love to be able to specify a locust population that:
-   increases to a certain level (at the specified hatch rate),
-   remains at that level for a specified time,
-   increases to the next level,
-   remains at that level for a specified time,
-   and so on until the specified population is reached.

I think you would need two more parameters, in addition to hatch rate and number of locusts: population_step and time_between_steps.

It would make the population grow like this:

```
|            _________   _
|        ___/            _|  population step
|    ___/
|___/_______________

     |__| time between steps
```

Instead of like this:

```
|      __________
|     /
|    /
|___/____________
```

**Comment by spearsem** [comment]
@justiniso Can this be re-opened? 

I am also curious about how to provide a fractional hatch rate, so that fewer than 1 VU is hatched per second (often, much fewer, like maybe 5 new VUs spread out over 1 minute).

You can see, e.g. in `bzt`, that [concurrency divided by the ramp-up time is always interpreted as a hatch rate, and the `math.ceil` means it cannot be less than 1](https://github.com/Blazemeter/taurus/blob/6c37d1bdad5476cbbf12105d1ed7fb3229236a16/bzt/modules/locustio.py#L84).

**Comment by vladbeza** [comment]
I am interested if someone found answer or some workaround for this feature. It would be useful

**Comment by vladbeza** [comment]
Found out that hatch rate may be set to float value so to get one user per 10 sec hatch rate 0.1 can be set. Maybe it will be helpful for somebody
