### ISSUE TITLE
Support for scenarios

### ISSUE THREAD

**Issue by pebo** [locustio/locust#171]
Is there a mechanism or a workaround for grouping a sequence of requests together as a scenario  / use case in locust?

It could be useful to be able to accumulate the total time for each request in a scenario and store this information in the stats api and ui, e.g:

- Scenario 1: Search for product (120ms)
 - GET /index.html  (10ms)
 - POST /search {json} (80ms)
 - GET /product/id  (30ms)
 - etc
 
- Scenario 2: Browse product (90ms)
  - GET /index.html (10ms)
  - GET /catalogue.html (50ms)
  - GET /product/id (30ms)
  - etc
  
- Ungrouped:
  - GET /foo. etc

**Comment by jverhoeven** [comment]
When it comes to enforcing an order within a scenario: A very simplistic solution would be to sort the task list and override the get_next_task method to pick the next task instead of a random one. Weighing factors would also still work. The sort method in the example below requires that you name your methods so they are sorted alphabetically, e.g. step1_index, step2_search, step3_product.

A better solution may be to define a task selection strategy in the TaskSet class.
```
from locust import HttpLocust, TaskSet, task

class UserBehavior(TaskSet):
    def on_start(self):
        self.tasks.sort()
        self.next_task_nr = 0

    @task(1)
    def scenario_step1(self):
        print "step1 should go first"

    @task(2)
    def scenario_step2(self):
        print "step2 should go twice"

    @task(1)
    def scenario_step3(self):
        print "step3 should go last"

    def get_next_task(self):
        task = self.tasks[self.next_task_nr]
        self.next_task_nr = (self.next_task_nr + 1) % len(self.tasks)
        return task

class WebsiteUser(HttpLocust):
    task_set = UserBehavior
    min_wait=1000
    max_wait=2000
```

**Comment by danmur** [comment]
Is there any reason it's not possible to do multiple things in a single task? e.g.

    @task(3)
    def login_and_news(self):
        self.client.get('/login')
        self.client.post('/login', {'username': 'test', 'password': 'blah'})
        self.client.get('/news')

Understand this is using gevent under the hood so it may not be so simple but it does appear on the surface to work, and from my experience with gevent I would expect it to.

**Comment by heyman** [comment]
@danmur Yes, that's perfectly fine. If one would like to report the total time in the UI, it could be done by manually triggering the `request_success` signal (http://docs.locust.io/en/latest/api.html#locust.events.request_success).

**Comment by CrispyByte** [comment]
@jverhoeven your sorting method breaks if any of the tasks contain response.success() or response.failure(). Is there's a way around this?

It'd be really useful if you could stop tasks being randomised as part of the api rather than having to devise hacky solution. Presumably the tasks starts off ordered. Why not add a flag to TaskSet to cater for this?

**Comment by jverhoeven** [comment]
@danmur, @heyman: Putting everything in one function breaks the nice interleaving between function calls that is provided by locust. In your example, when it starts all requests are executed back to back. Of course you can sleep between calls, but in order to have the same behaviour as with 'min_wait'/'max_wait' you have to add more logic.

@CrispyByte: Can you elaborate on the 'sorting method breaks'? The sorting is done only during script startup so I fail to see how it can break anything during running? Or do you mean that when a task failed before, picking that task again with 
`self.next_task_nr` = (self.next_task_nr + 1) % len(self.tasks)
will cause problems?

**Comment by CrispyByte** [comment]
@jverhoeven I have narrowed it down and, the problem seems within on_start. I have a loop that prints out self.tasks before sorting then after sorting. Sometimes it's ordered correctly after sort(), other times it's jumbled but in a new order.
Below is some code I'm using to test this. It's random whether it gets sorted. I find padding out functions with print statements or removing them can change the outcome. I'm running locust.exe on the Windows command line. Each time I quit out and run it again it's unpredictable if it's ordered.

Any clue why the sorting isn't always happening?

```
import os
import binascii
import json
from time import gmtime, strftime
from locust import HttpLocust, TaskSet, task

class PlayerTaskSet(TaskSet):

	playerID = None
	deviceID = None
	token = None
	tokenTime = None

	def on_start(self):
		self.index = 0
		print "----------[ BEFORE sort ]----------"
		self.printTasks()
		self.tasks.sort()
		print "----------[ AFTER sort ]----------"
		self.printTasks()

	def get_next_task(self):
		task = self.tasks[self.index]
		print "get_next_task index:%s task:%s" % (self.index, task)
		self.index = (self.index + 1) % len(self.tasks)
		return task

	def printTasks(self):
		i = 0
		for task in self.tasks:
			print "%s) %s" % (i, task)
			i += 1

	@task(1)
	def task000(self):
		print "task000"

	@task(1)
	def task001(self):
		print "task001"

	@task(1)
	def task002(self):
		print "task002"

	@task(1)
	def task003(self):
		print "task003"

	@task(1)
	def task004(self):
		print "task004"

	@task(1)
	def task005(self):
		print "task005"

	@task(1)
	def task006(self):
		print "task006"

	@task(1)
	def task007(self):
		print "task007"

	@task(1)
	def task008(self):
		print "task008"

	@task(1)
	def task009(self):
		print "task009"

	@task(1)
	def task010(self):
		print "task010"

	@task(1)
	def task011(self):
		print "task011"

	@task(1)
	def task012(self):
		print "task012"

	@task(1)
	def task013(self):
		print "task013"

	@task(1)
	def task014(self):
		print "task014"

class PlayerLocust(HttpLocust):
	task_set = PlayerTaskSet
	min_wait = 1000
	max_wait = 1000
```

**Comment by webtweakers** [comment]
@CrispyByte That's probably because multiple users are doing multiple requests at the same time. If you also print out self.locust, for example, you can follow the flow of a single user better and you'd see that the solution of @jverhoeven works perfectly.

**Comment by wessel-techtribe-nl** [comment]
self.tasks.sort returns a `TypeError: '<' not supported between instances of 'function' and 'function'` in python3.6 but works fine in python2.7

Replaced it with `self.tasks.sort(key=lambda t: t.locust_task_weight)`

**Comment by poobury** [comment]
Sorry to comment on such an old and closed issue but I was trying to achieve what the OP wanted regarding a single set of metrics (success/fail, total response time etc) for a group of API calls. 

@jverhoeven - I understand from your solution that it will order the tasks but I don't understand how it resolves the issue of single set of metrics for the group of tasks? That said, I am a newbie to Locust!

I've ended up following @danmur's suggestion of grouping all the API calls in a single task, timing them and firing a success/fail metric at the end as @heyman proposed (which ended up being quite a clean implementation with Python's decorator function annotations).
