### ISSUE TITLE
Remotely trigger load tests

### ISSUE THREAD

**Issue by elliotpryde** [locustio/locust#1797]
### Is your feature request related to a problem? Please describe.

To run Locust in an automated way (e.g. for a CI/CD pipeline) at the moment your only option is to run `locust --headless`. This has some limitations though

1. This command needs to be run on the master node, so it can't be run remotely unless you want to use SSH which is pretty non-standard
2. You need to spawn a new process to start a load test. This makes things tricky if you want to host Locust as a managed container.

### Describe the solution you'd like

It'd be perfect if there was a RPC API over HTTP to trigger new load tests. Even better if you could cancel a load test, get the load test status etc.

### Describe alternatives you've considered

Using something like [shell2http](https://github.com/msoap/shell2http) or creating my own HTTP server just to call `locust --headless`, but this would he hacky and insecure and I'd prefer a solution upstream for this rather than making my own.

**Comment by cyberw** [comment]
For distributed runs I recommend https://github.com/SvenskaSpel/locust-swarm/ (full disclosure: I wrote it :) It relies on ssh to start the worker locust processes, and can even run a remote master (again, over ssh)

I have also written an internal tool for triggering `swarm` (unfortunately not something I can open source, as it is integrated into a proprietary build system), but it is quite easy to wrap `swarm` in an HTTP api (the only hard parts is to parse the output, if you want to do additional processing of locust/swarm's headless output)

**Comment by cyberw** [comment]
> Even better if you could cancel a load test, get the load test status etc.

These are already possible using the locust web end points. But maybe you'd want to wrap them somehow, to expose them on the CI/triggering api.

I think this remote triggering API is highly dependent on what you would like to integrate it with. It would make sense to maybe  write a Jenkins plugin or something, but it is hard to do it in a generic way. 

Locust is inherently a shell level tool, and I've found that the most robust way to automate it is by actually running the shell commands. This has the added benefit of knowing exactly what command was executed, so that you can reproduce the same test outside of the CI/CD solution.
