### ISSUE TITLE
Specify `LoadTestShape` instead of having it declared in the locust file

### ISSUE THREAD

**Issue by joaonc** [locustio/locust#1829]
### Is your feature request related to a problem? Please describe.
When using a custom load shape (class that extends `LoadTestShape`), then the class needs to be specified in the locust file.
Per documentation [here](https://docs.locust.io/en/stable/generating-custom-load-shape.html):
> If this type of class is found then it will be automatically used by Locust.

I see 3 issues with this:
1. It's not very clear that the existence of the class in the locust file alters the test case load. A beginner would certainly miss this.
2. If you want to change the load shape, you need to edit the locust file.
3. You can only use that 1 shape class defined in the file.

### Describe the solution you'd like
I'd love to be able to explicitly declare which load shape class to use in a `User` class, similar to how we specify the `TaskSet` classes.
If not specified, then use the default.

```python
from my.shapes import Shape1, Shape2

class MyTest1(User):
    wait_time = constant(0.5)
    tasks = [UserTasks1]
    load_shape = Shape1

class MyTest2(User):
    wait_time = constant(0.5)
    tasks = [UserTasks2]
    load_shape = Shape2  # Different shape than in the other class!
```

### Describe alternatives you've considered
I'm working on a custom `LoadTestShape` that reads from a file, so I can change the load by changing the external users data file instead of the locust file, but I think native support in Locust would be a  lot better.

**Comment by joaonc** [comment]
This may be related to https://github.com/locustio/locust/issues/1734 (not sure).

**Comment by cyberw** [comment]
I definitely see the need for this, but it would be very complicated to implement (all the logic is based around having a total user count and weighted classes, not controlling ramp up per-user). Maybe after 2.0 is released we can look into this. The new user distribution method (with master in control instead of individual workers picking what to launch) should at least make it a little easier to do this.

**Comment by mboutet** [comment]
Also related to https://github.com/locustio/locust/issues/1583

**Comment by joaonc** [comment]
Is there a features list for later?  Otherwise this will be closed due to inactivity, like https://github.com/locustio/locust/issues/1583 was  (this is pretty much a duplicate).

Would love to see this implemented!

**Comment by cyberw** [comment]
There's not really a feature list. If you really want a feature you might have to build it yourself :)

Imo, #1583 was more about decoupling shape selection from locustfile selection, this one is more about having independent shapes for different Users.

It seems (to me) more related to https://github.com/locustio/locust/issues/575 (another abandoned ticket)

I'd love to see this feature, even without shapes it would be very useful to be able to say "I want X users of type 1 and Y user of type 2" instead of having to use weights. But someone needs to build it :)
