### ISSUE TITLE
semaphore wait not use on master with worker  run 

### ISSUE THREAD

**Issue by kyoliu** [locustio/locust#1856]
before run my  case  on locust 1.6  and use master-worker  semaphore wait (like examples/semaphore_wait.py )  is ok  

today  update my  locust to 2.1 semaphore wait  not use  when i run  on master-worker

python 3.7.8

**Comment by cyberw** [comment]
@mboutet Can you have a look?

**Comment by mboutet** [comment]
To summarize, the workers are not actually performing the whole ramp-up/ramp-down as of 2.0. Instead, each worker receives many small incremental ramp-up/ramp-down from the master. So, `examples/semaphore_wait.py` won't work as it did before 2.0 because the `spawning_complete` event on the workers will be fired for each of these incremental `spawn`. 

Here is a diagram I made some weeks ago to show how it works. Whenever a worker transitions from `spawning` to `running` the `spawning_complete` event will be fired on that worker.

![image](https://user-images.githubusercontent.com/52334444/130082583-18f032af-ffea-49da-98de-004b8cc7eed4.png)

I think the way to handle that as of 2.0 is to use [custom messages](https://github.com/locustio/locust/blob/master/examples/custom_messages.py). In essence, setup the `spawning_complete` event listener on the master which will send a custom message to the workers when fired.

**Comment by cyberw** [comment]
Very nice graph! Perhaps there are some places where the documentation needs to be updated? Does firing the spawning_complete event on workers even make sense any more?

**Comment by cyberw** [comment]
Or perhaps we need to do some extra work and pass the spawning_complete event from master to worker?

**Comment by mboutet** [comment]
If we want consistency between standalone and distributed mode, then passing the `spawning_complete` event from master to worker would probably be the best option.

**Comment by mboutet** [comment]
> Perhaps there are some places where the documentation needs to be updated?

If passing the `spawning_complete` event from master to worker is implemented, then the behaviour will be the same as pre-2.0. Thus, I don't think the documentation would need to be updated.

**Comment by kyoliu** [comment]
Thanks for reply , @mboutet  I try custom messages code ,  I don't understand how to implement this, in custom messages code 'usernames' arry mean about?   my case just need on_start time to prepare all user register (need 20000up so i need use master-work)
