### ISSUE TITLE
Load being distributed to missing workers too Version 2.7.4.dev14

### ISSUE THREAD

**Issue by radhakrishnaakamat** [locustio/locust#2008]
When running Locust in a distributed mode in Kubernetes, if the pod restarts then the worker status gets changed to missing. I can see that  spawning distributes the users equally to all workers, but in this case it distributes to missing workers as well which leads to reduced spwaning rate.
Kindly help!!
I have made some changes by adding Kubernetes support natively, have shared the details in slack channel. kindly suggest on how we can take this further.

**Comment by cyberw** [comment]
Hi! @mboutet is the person most with most insight into user distribution, but I think he'll need more to go on.

Perhaps you can write a failing unit test that shows your issue? https://github.com/locustio/locust/blob/master/locust/test/test_dispatch.py

(my opinion has always been that it is ok for locust to fail miserably if workers go missing in the middle of a test, because IMO that test is already invalid :)

**Comment by radhakrishnaakamat** [comment]
Closed this issue as it is linked with [2010](https://github.com/locustio/locust/issues/2010).

**Comment by mboutet** [comment]
Did you want to link the issue with the PR? If so, then you should simply add "Fixes #<the_issue_number>" to the PR's description.

**Comment by radhakrishnaakamat** [comment]
> Did you want to link the issue with the PR? If so, then you should simply add "Fixes #<the_issue_number>" to the PR's description.

Thank you, I was trying the same.

**Comment by mboutet** [comment]
If you're using PyCharm, you need to enable gevent compatibility in the [settings](https://www.jetbrains.com/help/pycharm/debugger-python.html).

For debugging the distributed scenario, your best bet is to write integration tests such as the ones in:
https://github.com/locustio/locust/blob/440c61206dc077841a1ac40b6c141c08ccc28635/locust/test/test_runners.py#L685

I don't think you're fixing the issue in the right place. The `UsersDispatcher` _should be_ alright. The issue is likely due to one or more bugs in the `runners.py` module.

Try to design integration tests such as the ones in
https://github.com/locustio/locust/blob/440c61206dc077841a1ac40b6c141c08ccc28635/locust/test/test_dispatch.py#L2220
that will reproduce the issue.

--- 

That being said, I experienced various issues like you have when running in k8s at my last job. I made a few "improvements" on my fork at https://github.com/locustio/locust/compare/master...mboutet:mboutet-master (I did not update the tests so they are failing at the moment).

The main changes are:

* Add the `LOCUST_WORKER_ID_OVERRIDE` environment variable on the worker so that a worker running in a pod can keep the same worker id across pod restarts. This needs to be combined with workers running in a stateful set.

* Implement a periodic rebalance background job (enabled using the `--enable-rebalancing` flag). This will rebalance the users every 10s.

* Implement a `rebalance_work_queue` (using `gevent.queue.Queue()`) that queues all the requested rebalances from the various places in the master. This queue prevents a bunch of rebalance from conflicting with each others. Instead, they are processed on a FIFO basis.

Obviously, these changes are highly experimental, but I found that they made Locust a lot more stable in a k8s environment with a lot of dynamic events such as restarting pods and auto-scaling workers.

Perhaps you could try my fork in your environment?

**Comment by radhakrishnaakamat** [comment]
> If you're using PyCharm, you need to enable gevent compatibility in the [settings](https://www.jetbrains.com/help/pycharm/debugger-python.html).
> 
> For debugging the distributed scenario, your best bet is to write integration tests such as the ones in:
> https://github.com/locustio/locust/blob/440c61206dc077841a1ac40b6c141c08ccc28635/locust/test/test_runners.py#L685
> 
> I don't think you're fixing the issue in the right place. The `UsersDispatcher` _should be_ alright. The issue is likely due to one or more bugs in the `runners.py` module.
> 
> Try to design integration tests such as the ones in
> https://github.com/locustio/locust/blob/440c61206dc077841a1ac40b6c141c08ccc28635/locust/test/test_dispatch.py#L2220
> that will reproduce the issue.
> 
> --- 
> 
> That being said, I experienced various issues like you have when running in k8s at my last job. I made a few "improvements" on my fork at https://github.com/locustio/locust/compare/master...mboutet:mboutet-master (I did not update the tests so they are failing at the moment).
> 
> The main changes are:
> 
> * Add the `LOCUST_WORKER_ID_OVERRIDE` environment variable on the worker so that a worker running in a pod can keep the same worker id across pod restarts. This needs to be combined with workers running in a stateful set.
> 
> * Implement a periodic rebalance background job (enabled using the `--enable-rebalancing` flag). This will rebalance the users every 10s.
> 
> * Implement a `rebalance_work_queue` (using `gevent.queue.Queue()`) that queues all the requested rebalances from the various places in the master. This queue prevents a bunch of rebalance from conflicting with each others. Instead, they are processed on a FIFO basis.
> 
> Obviously, these changes are highly experimental, but I found that they made Locust a lot more stable in a k8s environment with a lot of dynamic events such as restarting pods and auto-scaling workers.
> 
> Perhaps you could try my fork in your environment?

Thank you.. This is really helpful..

**Comment by b-heimann-senacor** [comment]
> The main changes are:
> 
> * Add the `LOCUST_WORKER_ID_OVERRIDE` environment variable on the worker so that a worker running in a pod can keep the same worker id across pod restarts. This needs to be combined with workers running in a stateful set.

I couldn't find information on this environment variable, is it still supported?

Currently, I am facing the issue that occasionally a Locust Worker loses connection to the Master and forever continues executing requests as an orphan.

**Comment by cyberw** [comment]
Disconnected workers should probably stop themselves after a while (maybe 60s?) but that is a different issue.
