### ISSUE TITLE
The latest docker image has a lot of vulnerabilities

### ISSUE THREAD

**Issue by tmokmss** [locustio/locust#2037]
### Describe the bug
When I run `trivy`, I get lots of finidings due to base image `debian 11.2`

```
locust (debian 11.2)
Total: 100 (UNKNOWN: 5, LOW: 69, MEDIUM: 6, HIGH: 9, CRITICAL: 11)
```

### Expected behavior
No findings are reported.

### Actual behavior
The actual findings are here: https://pastebin.pl/view/7218b865

### Steps to reproduce
Install trivy and run `trivy image locustio/locust`

### Environment

- OS: macOS
- Python version: n/a
- Locust version: (please dont file issues for anything but the most recent release or prerelease builds) 2.8.3
- Locust command line that you ran: n/a
- Locust file contents (anonymized if necessary): n/a

**Comment by cyberw** [comment]
If you can figure out where the vulnerabilities originate from (what package, or if they are in the base python image) then let me know. But even then, we probably wont be fixing that in this project.

If the vulnerabilities originate from Locust itself or there is a different image we could/should be using as base then maybe there is something we can do, otherwise I’ll be closing this as wontfix.

**Comment by tmokmss** [comment]
Hi, thank you for taking your time to check the issue.
Yes, all the vulnerabilities originate from debian:11.2, not Locust itself.
And I agree with you that there are not many things to be done about this issue from Locust side.

I guess the solution is that anyone who don't like these vulnerabilities introduced to their system will create their own Locust image.
