### ISSUE TITLE
Failure response time not displaying in UI.

### ISSUE THREAD

**Issue by breerly** [locustio/locust#207]
`locust.events.request_failure` takes `response_time` but does nothing with it.

In fact, the UI shows 0's even if a response time is reported with the `request_failure` event:

![screen shot 2014-11-26 at 1 51 59 pm](https://cloud.githubusercontent.com/assets/263587/5209438/72513006-7573-11e4-9e30-60dcd28329c3.png)

**Comment by lukerosenfeld** [comment]
I'm also having this issue. It makes me wonder if the failures that are also in the same line as some successful requests are being treated as if they have 0 response time. This would drastically skew data of the median, average, and min response times. Is there a fix to this?

**Comment by heyman** [comment]
Yeah, I think we should include the response time of failures as long as we get an HTTP response from the server, but not for other failures such as socket, dns, or connection errors. 

To achieve this we should make it so that *if* response_time is provided by the failure event, it'll be included in the stats. And then in the HTTP client make sure that we only provide response_time to the failure event when we've gotten an actual HTTP response.

**Comment by mikesss** [comment]
@heyman Yeah I think that makes a lot of sense

**Comment by vafliik** [comment]
Hi. Any chance that this will be resolved? I am using following code to (manually) trigger request failures

```
request_failure.fire(
    request_type='WebSocket Recv',
    name='app/api/async',
    response_time=666,
    exception="Something failed",
)
```
but it still displays 0 instead 666 as response time :(

**Comment by cyberw** [comment]
![image](https://user-images.githubusercontent.com/1134328/68485354-76f22f80-023f-11ea-9c52-474e3c4c441e.png)

Can't reproduce in current version.

**Comment by cyberw** [comment]
Maybe this was fixed a long time ago...
