### ISSUE TITLE
Locust never finishes starting

### ISSUE THREAD

**Issue by jkoorts** [locustio/locust#2257]
Hi I read the documentation:

Put the code in a file named locustfile.py in your current directory and run locust:

I do that it then says Starting Locust 2.13.0

The documentation then says "Once you’ve started Locust, open up a browser"

But nothing is printed after Starting Locust 2.13.0. Is it hanging at the starting phase and never goes to started?

When is it started?

**Comment by jkoorts** [comment]
Before that it also says Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces).

The never finishes, and if I click on the link I get 

This site can’t be reachedThe webpage at http://0.0.0.0:8089/ might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID

**Comment by jkoorts** [comment]
I press CTRL C then get:

Traceback (most recent call last):
  File "C:\Users\jkoor\AppData\Local\Programs\Python\Python311\Lib\site-packages\gevent\_ffi\loop.py", line 270, in python_check_callback
    def python_check_callback(self, watcher_ptr): # pylint:disable=unused-argument

I guess you can tell I'm new to python. I come from java - springboot world

**Comment by samuelspagl** [comment]
Hey @jkoorts, 

So if I understood you right, then you 
1. have an existing `locustfile.py`
2. started locust with `locust` command
3. got the message
```
[2022-11-17 08:00:25,950] MYMACBOOK/INFO/locust.main: Starting web interface at http://0.0.0.0:8089 (accepting connections from all network interfaces)
```

If these are correct, then locust is starting as expected. 
Try to call `localhost:8089` instead of `0.0.0.0:8089` as url for the browser. This should probably work. 

#### Explanation

Locust by default does not start a test by itself. Therefore one needs to visit the web-ui first to start it. 
You can take a look at this [🔗 documentation page](https://docs.locust.io/en/stable/quickstart.html) where the process is explained. 

If you don't want to use the web-ui, then you can start locust also in a [🔗 headless way](https://docs.locust.io/en/stable/quickstart.html#direct-command-line-usage-headless):
```bash
locust --headless --users 10 --spawn-rate 1 -H http://your-server.com
```


Hope that helps 😊

**Comment by jkoorts** [comment]
Hi its fine, someone else is taking over from this project. 

I now understand that 'starting' is meant to be 'started'. Don't agree with that. Other apps use the word "Started". There is more confidence in that.
