### ISSUE TITLE
return_response a valid request argument 

### ISSUE THREAD

**Issue by adrianlewis** [locustio/locust#229]
Is return_response a valid request argument? 
https://github.com/locustio/locust/blob/067c124d639055c309470377be650c9e99d726e8/locust/clients.py#L95

> TypeError: request() got an unexpected keyword argument 'return_response'

**Comment by heyman** [comment]
No, it's not. Good catch!

Since Locust mostly wraps python-requests part of that docstring had been copied from requests. Requests has changed it's method signature in later versions which Locust has upgraded to, without updating the docstring.

Thanks!

**Comment by adrianlewis** [comment]
Hi @heyman 

Is it possible to log the requests be sent in locust or do I need to drop down to python-requests?

**Comment by adrianlewis** [comment]
with self.client.get("/", catch_response=True) as response:
            print response.request.headers

**Comment by heyman** [comment]
Do you want to print log something for every request? There's different ways to go about that, but you shouldn't need to modify either locust nor python-requests.

For example, you could add a *get* method on your Locust class, which prints something and then calls `self.client.get()`. Something like this:

```python
class MyLocust(HttpLocust):
    def get(self, *args, **kwargs):
        response = self.client.get(*args, **kwargs)
        print response.headers
        return response
```

Then you'd have to update so that you'd use that method for making requests instead of `self.client.get`. If you don't want to do that, you could also make some kind of proxy object which you replace the *client* attribute with.

**Comment by adrianlewis** [comment]
@heyman Thanks for the advice. I just wanted to ensure the correct headers were being sent in the request.
