### ISSUE TITLE
pyproject.toml support for locust configuration

### ISSUE THREAD

**Issue by johnnymetz** [locustio/locust#2298]
### Is your feature request related to a problem? Please describe.

My project includes a lot of small configuration files. Many Python packages allow configurations to be included in `pyproject.toml` which helps reduce this config clutter and promotes consistency. See [PEP 518](https://peps.python.org/pep-0518/). Some of these packages include:

- [black](https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#black-compatible-configurations)
- [isort](https://pycqa.github.io/isort/docs/configuration/config_files.html#pyprojecttoml-preferred-format)
- [pytest](https://docs.pytest.org/en/7.2.x/reference/customize.html#pyproject-toml)
- [mypy](https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file)

### Describe the solution you'd like

Support configuration in `pyproject.toml`. Would be great to look for the config there by default (the locust config files can still take precedence) so users don't have to pass `--config=pyproject.toml` - other projects support this.

### Describe alternatives you've considered

None

### Additional context

I'm happy to work on this is needed.

**Comment by cyberw** [comment]
What would be required on locust side to support this?

**Comment by alzex3** [comment]
@cyberw Hello! First, I want to thank you for maintaining Locust; it has been very helpful in my work. It would be really cool to add the ability for Locust to parse configurations from `pyproject.toml` instead of requiring a separate config file.

I have checked the code. Changes would require modifying [argument_parser.py](https://github.com/locustio/locust/blob/cc5e373ab48f402918b8e6f5197d1c97b689074c/locust/argument_parser.py). The Locust arguments parser uses the [configargparse](https://github.com/bw2/ConfigArgParse) lib, which already has a built-in TOML parser, so there shouldn't be a lot of code changes.

I would be really glad to contribute this feature if it's welcome. I'm waiting for your response, thanks!

**Comment by cyberw** [comment]
A PR would be most welcome!
