### ISSUE TITLE
Parameterizing each Locust on a distributed load test

### ISSUE THREAD

**Issue by lieryan** [locustio/locust#233]
When running distributed load tests that that requires exclusive access to a limited resource, a Locust need to be able to check out a set of resources to exclude other Locust from working on the same resource and return the resource to the resource pool when the Swarm is downsized so the resource can be used by another Locust when the Swarm increases in size again or when the Locust dies.

Example:

``` python
def on_start(self):
    self.locust.appuser = self.appuser_resource.check_out()

@task
def do_task(self):
    do_something(self.locust.appuser['username'], self.locust.appuser['password'])
    do_something_else(self.locust.appuser['username'], self.locust.appuser['password'])
```

In the above scenario each Locust will run a single `appuser` and no other Locust should be running with the same appuser at the same time.

In a single-process scenario, this can be done fairly easily by having a global dict that keeps track of the actively used resource, but in a distributed test, since each Locust slaves have its own set of globals, modifying the globals in one slave does not modify the globals in the other slaves.

**Comment by justiniso** [comment]
Good question! Because of the distributed nature of locust, you'll need some sort of external store to keep track of your resources. Something like [redis](https://redis.io/) would work pretty well. Just store a boolean value with `username` as the key. You could even set an expiry in case locust dies without "checking back in" the user.
