### ISSUE TITLE
Slack channel signup issue

### ISSUE THREAD

**Issue by ishan-12** [locustio/locust#2368]
Hello, I am trying to sign up for the Slack channel here: https://locustio.slack.com/. But I get Error: 

`"<email>@gmail.com doesn’t have an account on this workspace. `

How do I get an account for the locust workspace? 

Note: I have tried with multiple email addresses to try to get in but getting the same error for every email address that I have tried.

**Comment by cyberw** [comment]
Try contacting Slack support. We dont really control slack user accounts or anything.

**Comment by cyberw** [comment]
Huh. I just realized that you need an invite to get in. Here's one for now, @ishan-12

https://join.slack.com/t/locustio/shared_invite/zt-1ytkc18eq-GnxDDF5xhH5cXn3S0npKAw 

I've pinged @heyman about it.

**Comment by heyman** [comment]
A long time ago I set up and app (https://github.com/outsideris/slack-invite-automation) on https://slack.locust.io/ to allow anyone to "invite themselves". However, I can see that it doesn't seem to work anymore :/.

**Comment by cyberw** [comment]
Now anyone should be able to join using https://communityinviter.com/apps/locustio/locust

**Comment by ishan-12** [comment]
Thank you @cyberw and @heyman. I am in the Locust channel now.

**Comment by Badam4321** [comment]
have executed the test with the parameters below and observed more requests in the report. Can anyone explain why this is happening? Also, if I want to achieve the exact number of requests, what should I do?

test_parameters = {"test_duration": 60,
                   "users_count" : 50,
                   "users_spawn_rate" : 5,
                   }
I am attaching the result report please assist me 
It should run 50request for the 60s.This is the expected behavior
