### ISSUE TITLE
Locust grpc node can't handle more than 210 rps

### ISSUE THREAD

**Issue by ibrahiem94** [locustio/locust#2369]
### Describe the bug
 I followed the example of grpc client and using gevents 
 
```
# patch grpc so that it uses gevent instead of asyncio
import grpc.experimental.gevent as grpc_gevent

grpc_gevent.init_gevent()

```
The node can handle only 210 rps and we should be able to handle 40k does it means we should have 200 nodes to be able to load test !

### Environment

- OS: Docker 
- Python version: 3.9
- Locust version:  2.15.1
- Locust command line that you ran: docker-compose up --scale worker=20
I tried it as well locally without docker same throughput

**Comment by dhm116** [comment]
For context, we were able to achieve 50k (50,000) req/sec over gRPC (with TLS) however this required 48 Locust worker nodes and 24 gRPC Golang servers (with a GCP Internal load balancer backed by Envoy between them). Locust was definitely the bottleneck in the load test, however this was to be expected since it's python-based 🤷 

I have never run into a situation where only 210 req/sec was observed (with gRPC), but there are still a number of variables that could influence that...

**Comment by cyberw** [comment]
Is it possible the bottleneck was `inspect.currentframe().f_back.f_code.co_name`? Have you tried without it?
