### ISSUE TITLE
recommended AWS EC2 instance types?

### ISSUE THREAD

**Issue by aztlan2k** [locustio/locust#242]
I've been running locust on ~20 `m3.large`  (2 cores) EC2 instances recently and I noticed that locust was cpu bound to a single core (_100% utilization of_ **only** _a single core with the 2nd core being almost completely idle_).  I started to wonder what the ideal EC2 instance type would be for driving locust load tests.

Does anyone have any experience with running on different types of EC2 instances?  Any recommendations on which works best?

My assumptions are that **multiple cores** aren't an issue, unless you're running multiple instances of a slave on the same box and that **memory** and **storage capacity** aren't issues.  Would **networking** throughput be the main factor?

Any info / suggestions / discussion would be greatly appreciated.

**Comment by cgoldberg** [comment]
I recently started running on AWS and am also curious about recommended instance types.

I think locust would be network I/O bound unless you use instance types with "Enhanced Networking" and you are generating load towards a host within the same AWS region.

Since locust does async i/o, adding cpu cores shouldn't be beneficial.

**Comment by aztlan2k** [comment]
@cgoldberg  yeah, i pretty much agree with your assessment.  I just wonder whether anyone has done any comparisons / analysis with different instance types and might have any recommendations.  

Unfortunately, when I look at the instance type specs, when it comes to networking (non-"Enhanced Networking) all I can see is either "moderate" or "high" for networking performance, which isn't very descriptive and therefore not very helpful.  

If you don't mind sharing, what types of instances do you typically run with?

**Comment by heyman** [comment]
Hi!

In order to utilize multiple CPUs, one should run one Locust slave per core. 

I can't say what type of EC2 instance is the best for every case, since it depends on the load testing scripts. However, from my experience, Locust test suites are usually CPU bound. Therefore, I would recommend starting with one of the "Compute Optimized" EC2 instance types, and then monitor memory and network usage, to make sure that none of those gets maxed out while running the tests at full load.

I've been part of running huge load tests, and we've never had to use Enhanced Networking.

**Comment by aztlan2k** [comment]
Thank you @heyman .  I appreciate the input.   I'll be trying some of this out next time I have to do a test run.

**Comment by trienism** [comment]
I've been using c4.2xlarge and run locust in masterless mode across multiple cores using the multiprocessing library. It works pretty well until the number of reaches exceeds 5000.

**Comment by eezis** [comment]
@trienism do you have a code snippet for running locust using the multiprocessing library?
