### ISSUE TITLE
Modern UI: Lack of information about time and user count in charts

### ISSUE THREAD

**Issue by zifter** [locustio/locust#2467]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

In Modern UI in charts there is no information about user count and time

Expected:
![image](https://github.com/locustio/locust/assets/1105370/3337cc47-5a03-4230-b08f-d8bb321ba562)

Result:
![image](https://github.com/locustio/locust/assets/1105370/e3ecaef6-93b0-45c9-9442-7c4e457444b0)

### Command line

-

### Locustfile contents

```python3
-
```

### Python version

3.11

### Locust version

2.18.3

### Operating system

linux

**Comment by cyberw** [comment]
Thanks for the report! @andrewbaldwin44 , when you have the time...

**Comment by cyberw** [comment]
@zifter Looking at your screenshot, the RPS is visible. Did you mean User count and timestamp? Or am I missing something :)

**Comment by zifter** [comment]
@cyberw yes, time and User count. Miswrite in description, title still correct

**Comment by andrewbaldwin44** [comment]
@zifter @cyberw In my opinion I find the repetition of the user information to be a bit redundant when you can easily see the information in the last chart (because the charts are connected, hovering over any value in one chart highlights the value at the same timestamp in the other charts). Let me know what your thoughts are on this,

I added the timestamp to all tooltips :)
