### ISSUE TITLE
Unifying percentile displays in Locust's statistics screens

### ISSUE THREAD

**Issue by FooQoo** [locustio/locust#2546]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am suggesting a new feature, not asking a question

## Summary
I have noticed a lack of consistency in the percentile displays on Locust's UI statistical screens. Specifically, there is a discrepancy in the percentiles displayed between the overall statistics screen (statics) and the screen that records the time series change of statistics (charts).

### Current Display
- Statics screen: Median/90%ile/99%ile
- Charts screen: Median/95%ile

## Proposed Changes
To achieve a more consistent data analysis experience, I propose the following changes:
1. Add 95%ile to the Statics screen.
2. Add 90%ile and 99%ile to the Charts screen.

These changes will unify the percentile displays across both screens, making it easier for users to compare data between different screens.

## Expected Impact
With these changes, users will find it easier to compare statistical data across different screens. This will lead to more comprehensive and accurate performance analysis, and is expected to improve the overall usability of Locust.

**Comment by cyberw** [comment]
Graphing percentiles over time is kind of a weird thing, as the average 95th percentile over a run is not the same as the 95th percentile for the whole test.

And with few requests per time interval, percentiles are likely to be all over the place, especially higher percentiles (that's why we dont use 99th in the graph) 

I kind of think the current choice of percentiles make sense, but I get that they feel inconsistent. Adding 95th percentile to the stats screen by default makes some sense though (btw, these are all configurable https://docs.locust.io/en/stable/configuration.html#customization-of-statistics-settings)

**Comment by cyberw** [comment]
What do you think @andrewbaldwin44 ? Maybe we should replace 90th percentile in the stats with 95th just to make it consistent? There's already so many columns in that page :) Maybe add a link to the customization documentation on that page too, I think it would be really useful...

**Comment by andrewbaldwin44** [comment]
I agree with you @cyberw, if it is already configurable in both the table and the charts, I'm not sure if it makes for us to change it. Especially considering that different users will always have different opinions on what columns should be displayed.

I have another suggestion here, what would you think of allowing the users to select which columns they want to be displayed. I've seen some other load testing tools offer this feature and I think it could be useful to allow the user to focus on the data they care about

**Comment by cyberw** [comment]
I was thinking about that. If it can be done without becoming messy it would be great!

**Comment by FooQoo** [comment]
@cyberw, @andrewbaldwin44

Thank you for guiding me through the customization process. Following your instructions, I was able to successfully customize the charts screen. I hadn't fully grasped that the 95th percentile was already adopted in the charts screen, but after your explanation, I now understand the appropriateness of this choice.

Additionally, as @andrewbaldwin44 suggested, adding the ability for users to edit columns in the statics screen, similar to the charts screen, would greatly enhance convenience. I would be delighted if this suggestion were implemented. It would allow users to focus more on the data that matters to them, thereby significantly improving the Locust user experience.

**Comment by FooQoo** [comment]
This issue has been resolved by PR #2550, so I close it.

**Comment by cyberw** [comment]
Hi @FooQoo (hoping this reaches you, and I dont really have any other way to contact you :)

Are you a regular user of locust? Would you like to give the project a little help by giving us a quote to put on our web page?

you can say whatever you want but if you want some inspiration: `At <your company/organization> we use Locust to ensure the performance of our systems. We chose it because it is <flexible/developer friendly/something else> - Satoshi Fukuyama @FooQoo`
