### ISSUE TITLE
Modern UI: Average Response Time and 95th percentile have the same color

### ISSUE THREAD

**Issue by zifter** [locustio/locust#2598]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

Average Response Time and 95th percentile have the same color.
<img width="1439" alt="image" src="https://github.com/locustio/locust/assets/1105370/0c3c5f04-7d30-4e28-859c-0fdacdcc2275">

Actually, is it possible to turn off average response time?

### Command line

-

### Locustfile contents

```python3
-
```

### Python version

3.11

### Locust version

2.23.0

### Operating system

-

**Comment by andrewbaldwin44** [comment]
Thanks! I knew on the old UI we used to limit the percentiles display to two, I forgot we didn't set a limit on the new UI. How does something like this look? (I will set a limit to 6 percentiles)
![image](https://github.com/locustio/locust/assets/59211596/a664d8f7-e6a6-4a83-9ad9-f532114ed6cb)

As for the average, there isn't currently a way to disable it. The reason is because `PERCENTILES_TO_CHART` only accepts integers. Most likely we would need to set a boolean or create a new argument in order to be able to disable showing the average. What do you think @cyberw? Should we have a way of disabling showing the average stat in the charts?

**Comment by cyberw** [comment]
The suggested colors look great imo :)

I'm in no rush to add a feature to disable average.
