### ISSUE TITLE
Windows Action Runs Wrong Version of Locust

### ISSUE THREAD

**Issue by andrewbaldwin44** [locustio/locust#2796]
### Prerequisites

- [X] I am using [the latest version of Locust](https://github.com/locustio/locust/releases/)
- [X] I am reporting a bug, not asking a question

### Description

When breaking the tests https://github.com/locustio/locust/compare/master...andrewbaldwin44:locust:bug/windows-action the Windows test action will not fail

![image](https://github.com/locustio/locust/assets/59211596/d8f5cc4d-b51c-4fd8-bd84-64233fbeeda5)

@mquinnfd This should be poetry related, any idea?

### Python version

3.12

### Locust version

2.29

### Operating system

Windows

**Comment by mquinnfd** [comment]
Hey @andrewbaldwin44 I'll push something to replicate this, would be good to see the logs from the failing action 🧑‍💻

**Comment by mquinnfd** [comment]
I think this is because...
- For Windows builds, we added a step to `build` & install the `locust` package, to put the current version on the `PATH`
- This is because `poetry install` did not appear to add `locust` to the `PATH` so caused tests to fail
- Running `poetry build` on the Windows runner, will mean that the front end build is run
- The version of `locust` used by the `fail_fast` tests will be the one that was build and installed as a package, not a dev install

So, in terms of what to do with this, the best way is probably to find the editable install location on the Windows runner, and add this to the `PATH` so the `fail_fast` tests can run. I avoided this initially because it might look a bit grim in the runner `steps` but it does make this build more predictable

**Comment by mquinnfd** [comment]
Definitely fixable I'll just need to run this on my Windows machine to check the commands work

**Comment by andrewbaldwin44** [comment]
Hey @mquinnfd, sorry about that I should have sent this link as well https://github.com/andrewbaldwin44/locust/actions/runs/9840186826/job/27163841986. The logs from the actions could have been seen on my fork but no matter :)

I think no frontend being built on Windows is not really an issue since we don't need the frontend for `fail_fast` right?

**Comment by mquinnfd** [comment]
![image](https://github.com/locustio/locust/assets/82032454/7e54857a-e621-4ac4-9ac6-615d9b0a7993)
Didn't realise I could see your fork's actions, sorry

Yeah that's true - it was building this for the `build` step though, so tried removing it but it still doesn't fail the test.

It's a little bit weird, but I suppose the rub is that `poetry build` is overriding the output of `poetry install` here in ways which are not cool.

I tried making these in parity, technically you would expect these to function the same, but I guess not. I'll need to write up something that ensures the binary/symlink created by `poetry install` is available on the runner's `PATH`.

This probably boils down activating the `venv` or something 🤔

**Comment by andrewbaldwin44** [comment]
Yeah I was also thinking that activating the venv could have something to do with it, but I was thinking that if it was an issue with venv, then we should see an error such as `'locust' is not recognized as an internal or external command`

**Comment by mquinnfd** [comment]
Hey @andrewbaldwin44 to follow up on this:

I tested this code change on my Windows machine this morning - interestingly I cannot actually get the fail-fast (`tests/test_main.py`) to break with this change. I tried this by doing the same thing the Windows runner is doing, building and installing it so that the tests can call `locust` on the path.

Do you know which tests you expect to break on this change? I note that 21 tests are skipped on the `nt` platform, citing signal handling problems - it could be that the tests in these blocks are the ones that would fail without the web UI being set, maybe?

---

I tried a few ways of getting `locust` on the path for the tests without this build, the Windows `cmd` shell is just horrible for trying to do this neatly, and would probably need to either revise the virtual environments for the steps or write a batch script...

**Comment by andrewbaldwin44** [comment]
Yeah so that's actually exactly the problem :) The fact that the tests _should_ fail and they are not failing indicates that the Locust version being used is incorrect. We were actually able to reproduce this in several ways, here's another example:

https://github.com/locustio/locust/compare/master...test-tests in this example the Windows tests are failing even when they should be passing https://github.com/locustio/locust/actions/runs/9840237867

**Comment by andrewbaldwin44** [comment]
Yeah the Windows shell is quite horrible I really don't understand how anyone is able to use Windows without WSL haha. I have a Windows VM on my side as well, I don't know as much about poetry as yourself but I will try to help if I can!

**Comment by mquinnfd** [comment]
Should be fixed in https://github.com/locustio/locust/pull/2803 @andrewbaldwin44  might be OK to close
