### ISSUE TITLE
Load testing a site whose domain name is not pointed/registered . 

### ISSUE THREAD

**Issue by rjdp** [locustio/locust#326]
I tried putting entry in /etc/hosts for the site but , the request were going to original site . I will explain with an example:

* Lets my site name google.com(mentioned  as argument to `server_name` directive in vhost's nginx configuration)  hosted on a vps with IP `abc.efg.ijk.lmn`

* In my `/etc/hosts` I have put an entry `abc.efg.ijk.lmn   google.com` .

* I have `abc.txt` file in `htdocs` of my site google.com, and I am able to access it using google.com/abc.txt .

I have `task` in my `locust taskset` that is programmed to hit `google.com/abc.txt`

but when  i run `locust --host=http://google.com`

but request is going to THE `google.com` 

any help would be greatly appreciated

**Comment by kevbo** [comment]
Arg, I think I just discovered this as well. I pushed a pretty long hosts file to /etc/hosts on a bunch of slaves with ansible, but was only seeing a little traffic show up on the targets. When I did a tcpdump, I saw traffic going to the datacenter that's registered in public DNS. I guess I'm going to go digging into the source now, but please respond if you've worked around this or have a fix.

**Comment by mthurlin** [comment]
Locust uses gevent internally, and I know gevent has been having issues with DNS previously (pre 1.0):
http://www.gevent.org/whatsnew_1_0.html#new-dns-resolver

These should have been fixed with gevent 1.0, but you can try setting the environment variable:

    GEVENT_RESOLVER=ares

and see if that helps.

You could also try making request with/without gevent from the python REPL to see if there is any issues there, or if it is related strictly to locust
