### ISSUE TITLE
Unix timestamp in stats/requests

### ISSUE THREAD

**Issue by aidylewis** [locustio/locust#332]
I'm polling the JSON block in stats/requests, but I'm creating my own Unix time: 
https://github.com/bbc/locust-load-tests/blob/master/tests/lib/stats.py#L30

I wondered if you can add the Unix time to the API to avoid any time lag issues that may occur.

**Comment by vividhsv** [comment]
Yes, It would help if Unix time stamps are added.

As a work around you can also listen for slave_report event and collect the stats and push them to Graphite or Influx. Since the Slaves send stats with timestamp you wont have any time lag issues. (NOTE: This works only with distributed setup)

Here is a sample from my code

**Comment by aidylewis** [comment]
Hi @vividhsv 

Could you add the sample code please?

**Comment by vividhsv** [comment]
Sorry, edited the commet above ..Hope it helps.

**Comment by aidylewis** [comment]
Thanks for the example.

**Comment by cgoldberg** [comment]
nice!
