### ISSUE TITLE
How do I start a new session

### ISSUE THREAD

**Issue by anabuki** [locustio/locust#356]
Hello,

I am trying to start a load process but I want to test not only my application but also my authentication infrastructure. I want my webserver to authenticate every request instead of reusing sessions. I am testing a rest api that uses basic authentication.

The idea is that I have millions of mobile users making a single request by day instead of a few thousands making constant use of the application. 

Can anyone help me ?

**Comment by vividhsv** [comment]
From requests documentation it can be seen that requests.Session class has close() method. You can probably call slef.client.close() after each request so that new connection are made for each request.

I have never tried this, just an idea.Let me know if it works. More on this can be found in the documentation.
http://docs.python-requests.org/en/latest/api/#requests.Session

**Comment by anabuki** [comment]
Thanks man!! I am going to make some changes to my script to adapt better for my tests but for the time being it is working beautifully :)
Really appreciate the help :)

**Comment by BrandonLiang** [comment]
Hi, were you able to get it to work? If so, could you share you script?

https://docs.locust.io/en/stable/_modules/locust/contrib/fasthttp.html#FastHttpUser.rest, `FastHttpSession` (`FastHttpUser.client`) has no method `close()`
