### ISSUE TITLE
Integration with CI and test frameworks

### ISSUE THREAD

**Issue by rfjuris** [locustio/locust#385]
Hi,

Trying to evaluate locust.io for our perf-testing needs. Have a couple questions to authors and community:

1. I was wondering if someone has had experience integrating locust.io into Jenkins CI? Any pointers?
2. Integration to (unit)test frameworks like nose, pytest, Behave? Anyone done that successfully?

Point 2. actually boils down to requiring test level setup/teardown hooks that would set-up system under test to a required state before test and then afterwards do the cleanup. Maybe locust.io already provides this kind of functionality?

Thanks!

**Comment by gunesmes** [comment]
You may check this post for integrating to Jenkins:

http://www.testrisk.com/2016/01/performance-testing-on-ci-integration.html?m=1

**Comment by pglass** [comment]
I run locust from jenkins. It's not exactly a fun time, but with some effort it works.

You can accomplish the basic things out of the box. You can administer locust via its api from jenkins to start and stop and the test (`POST swarm` and `POST /stop`). When the test is finished, you can fetch the response time and percentile data via the api as well, and store them wherever you like. This is fairly straightforward and gives you control to adjust the request rate (number of locust users) from a jenkins parameter.

On point two, I use the jenkins build flow plugin to orchestrate pre-test and post-test actions that run as isolated jenkins jobs. I actually deploy our locust cluster on-demand via ansible which allows me to easily reconfigure the test via job parameters in jenkins (since you need to point locust to a single file containing a single test configuration).

**Comment by rfjuris** [comment]
@gunesmes Thanks for the link!

@pglass One thing that bothered me when running locust in no-web mode was the absence of results in csv, but as you mentioned, it can be done via AP call. Not elegant, but I suppose I can make it work.
