### ISSUE TITLE
Webclient authentication

### ISSUE THREAD

**Issue by michaelsharpe** [locustio/locust#406]
I am using Locust to set up load testing for a client, but one requirement I have is that the Webclient needs to be password protected so that not just anybody can go to the URL and initiate a load test.  Is there any way to do this?

**Comment by justiniso** [comment]
Where are you hosting your web client server? Generally you would want to keep that within a private network.

**Comment by michaelsharpe** [comment]
Both my locust server and the API I am load testing are both living on AWS.  The API won't be publicly exposed, but the locust interface will be so that the client can easily access it.  I was hoping there was a feature like Basic Http Auth in Flask so that I can secure the Locust GUI.

**Comment by justiniso** [comment]
There's no reason the web interface couldn't include basic auth, but I think that's a rare use case since most people use locust internally or destroy the master when they're done with it. 

I would recommend putting nginx in front of your locust server, which has much better auth support and is something you could set up today rather than waiting for auth to be tested and released.

**Comment by justiniso** [comment]
You can also look into setting up a VPC with Amazon: https://aws.amazon.com/vpc/

**Comment by michaelsharpe** [comment]
Great!  Thanks for the help Justin.  I will take a look into the Nginx route, as I am already running it with nginx, though i am new to it so I wasn't aware of that feature.

**Comment by justiniso** [comment]
Here are the docs to get started: http://nginx.org/en/docs/http/ngx_http_auth_basic_module.html
