### ISSUE TITLE
Export exceptions to CSV didn't work

### ISSUE THREAD

**Issue by threatstop** [locustio/locust#412]
I ran some testing the the day and got great results. The tool is awesome. 

However, I was unable to export the exceptions to CSV. The headers were written, but the data was not there. The other two exports worked fine.

Was on Latest release
Master slave setup (master + 2 slaves)
Running on ubuntu 14.04
Python 2.7.4

**Comment by cgoldberg** [comment]
weird...
are you sure exceptions actually occurred during the test run?

I'm asking because this feature was added quite a while ago, and all tests are still passing.

the export csv feature was introduced with this commit:
https://github.com/locustio/locust/commit/2dbdb266efda046382efa60938bd38a5eb6097d5

the latest CI build against master had all test green (see `test_exceptions_csv` ):
https://travis-ci.org/locustio/locust/jobs/120318391#L806

**Comment by justiniso** [comment]
@threatstop were you downloading through the browser or using some sort of HTTP client? If browser, the obvious question is which browser/version. Either way, can you grab the full response and paste it here?

If you still have any debugging info, please reopen the issue so we can investigate!
