### ISSUE TITLE
self._sleep() should not be private.

### ISSUE THREAD

**Issue by robvdl** [locustio/locust#550]
It would be much better just to remove the underscore, I am calling it a bit from my tasksets, not sure why it's even private.

**Comment by cgoldberg** [comment]
You can get a similar effect using `wait()`, and setting your TaskSet's `min_wait` and `max_wait` set to the same value.

however, see `/locust/core.py` ... there are some subtle differences between `_sleep()` and `wait()`, and I'm not sure using sleep is really what you want.

**Comment by heyman** [comment]
Using `TaskSet._sleep()` is exactly the same as calling `gevent.sleep()` which is the same as calling `time.sleep()` (since it's been monkey patched by gevent). Actually I think we could consider removing `_sleep()` and instead calling `gevent.sleep()` directly.

**Comment by jessebrennan** [comment]
My particular use case for this was I wanted to sleep while within a task because some endpoints I'm testing give a `retry-after` header. It seems like just calling `self._sleep()` (or even `gevent.sleep()`) accomplishes exactly what I'm looking for.

Maybe this case is atypical, but also I don't see a problem making it a public part of the API.
