### ISSUE TITLE
Locust web interface not starting on Windows

### ISSUE THREAD

**Issue by animtechdebt** [locustio/locust#57]
```
C:\Development\Test>locust -f main.py
[2013-02-27 19:30:11,346] INFO/locust.main: Starting web monitor on port 8089
[2013-02-27 19:30:11,348] INFO/locust.main: Starting Locust 0.6.2
```

...And then it never gets past this point. I am using the example locust file from the website for main.py 

```
from locust import Locust, TaskSet, task

def index(l):
    l.client.get("/")

def stats(l):
    l.client.get("/stats/requests")

class UserTasks(TaskSet):
    # one can specify tasks like this
    tasks = [index, stats]

@task
def page404(self):
    self.client.get("/does_not_exist")

class WebsiteUser(Locust):
    host = "http://127.0.0.1:8089"
    min_wait = 2000
    max_wait = 5000
    task_set = UserTasks
```

I am running Windows 7. Any ideas on what I could be doing wrong? Would be happy to clarify more information.

**Comment by konstantinosalvertis** [comment]
Hi there,
I have a similar question like above , the locust web interface does not appear.

Here are details for my try:
Recently i installed locust in windows and i used the [http://docs.locust.io/en/latest/quickstart.html](url) quickstart.
Currently i have locally a web application running in http://127.0.0.1:8080.
So i used the command line and i navigated to the directory with the file locustfile.py.
Subsequently i executed the command:   locust --host=http://127.0.0.1:8080

Unfortunatelly the http://127.0.0.1:8089 link does not display the locust web interface.
Do you have any idea what is the root cause and how to resolve it.

Thank you

**Comment by thanhma** [comment]
I had the same problem.

After hopeless searching, I tried navigating http://localhost:8089 and web interface appeared like miracle.

Give it a try guys.

**Comment by frostHit** [comment]
i have the same issue on windows7.
i follow the example in the quickstart  http://docs.locust.io/en/latest/quickstart.html
and type locust in the windows cmd window. it shows starting web monitor at *:8089 but failed to get it the web page on localhost:8089

**Comment by frostHit** [comment]
@konstantinosalvertis hi, did you close this issue?  i am facing the same issue.

**Comment by cgoldberg** [comment]
> but failed to get it the web page on localhost:8089

@frostHit I don't know what that means.  did you open a browser and try loading http://localhost:8089?

btw, this issue was closed over 5 years ago.  Please open a new one if you actually have an issue.

**Comment by konstantinosalvertis** [comment]
@frostHit Hi, I couldn't find any workaround for the issue as I remember related to windows 7. Subsequently I set up a Linux server and locust worked fine.

**Comment by NullP0inter** [comment]
Strange http://127.0.0.1:8089/ doesn't work but http://localhost:8089/ does.
