### ISSUE TITLE
Summary result

### ISSUE THREAD

**Issue by Cyansilver** [locustio/locust#578]
hi, 

I would like to ask about the report result, sometimes there are some rows show all 0 in min, max, mean, .... I wonder what its meaning because when I check the request it's done successfully. Thanks

**Comment by aldenpeterson-wf** [comment]
Can you provide more information so this can be reproduced?

How are you causing this?

**Comment by Cyansilver** [comment]
hi aldenpeterson-wf,

I think it happens when the locust hatch all users and reset the stats but I wonder if in this case, the report is no longer correct so how we handle this case?

Another case may be the response time is too small so the min shows 0.

**Comment by worldomonation** [comment]
When I implemented an instance of Locust that used WebSocket calls for my company, it did come out as 0 for all unless I manually handled the response times due to WebSockets communicating in microseconds.

I have also ran into situations where number of users was large and spawn rate too low, that it by the time all users spawned the testing phase was essentially over. Locust would still reset the stats so in that case, I'd see something like 20 requests made vs. an 20k that was expected.

In both cases Locust is working as intended :)
