### ISSUE TITLE
reqs/sec is lower than other tools result

### ISSUE THREAD

**Issue by DreamBe** [locustio/locust#586]
reqs/sec is lower than other tools result: Apache Bench, Jmeter etc.
For the same API, the result can be 6000 reqs/s but less than 3000 reqs/s when I use locust( 8 slaves).
More details:
My local machie's CPU all run 100%
I wonder is there some wrong setting that I have make.

My code is below, and my set is 400 Users\ 4000 Hatch rate with 8 slaves.

```
from locust import HttpLocust, TaskSet, task

class UserBehavior(TaskSet):

    @task
    def getDeviceConf(self):
        url = 'http://exaple.com?xxxx'

        with self.client.get(url, catch_response=True) as response:
            if response.status_code == 200:
                response.success()

class ClientUser(HttpLocust):
    task_set = UserBehavior

    min_wait = 1000
    max_wait = 1000
```

**Comment by heyman** [comment]
If your CPUs are maxed out, that's probably the bottleneck. It doesn't sound strange that you can achieve higher reqs/s with some other tools. Locust's main purpose isn't just to achieve as high reqs/s as possible (if that were the case, python would probably be a bad choice of language). Instead, Locust focuses on letting you define *user behaviour* using python code to create realistic load tests, and in general favors developer friendliness over performance.

One thing that can be done to improve the performance by quite a bit, is to use geventhttpclient (https://github.com/gwik/geventhttpclient) as the HTTP client, instead of requests. The reason Locust doesn't use it by default is that requests provides a much nicer API for the developer, and the optimization is unnecessary in most cases.

**Comment by DreamBe** [comment]
It's very kind of you to explain this, this will be much useful for me.
Let me try the method that you give.

发自我的 iPhone

**Comment by hkandukuri** [comment]
@heyman 
Can you please point me to an example script, similar to the above one, of locust+geventhttpclient?

Thanks, 
HK

**Comment by heyman** [comment]
@hkandukuri Use the geventhttpclient branch: https://github.com/locustio/locust/tree/geventhttpclient and then import `locust.contrib.fasthttp.FastHttpLocust`.

**Comment by sj2208** [comment]
@heyman  - Is there any utility written to cast geventHttpclient response to HttpLocust Response ?
We have test suite with around 70 odd locust scripts using HttpLocust Response. It will be of great help if we can somehow cast geventHttpClient response to the existing HttpLocust ?

**Comment by hkandukuri** [comment]
@heyman How to use the geventhttpclient branch from https://github.com/locustio/locust/tree/geventhttpclient, i new to python.

I was able to install geventhttpclient directly and use its HTTPClient, but can you explain on how to use FastHttpLocust.
