### ISSUE TITLE
locust doesn't record all the requests

### ISSUE THREAD

**Issue by Chrisbuuren** [locustio/locust#615]
Hello all, 
I am using locust and there is a problem with the total number of requests recorded by the API and WebUI.
I started a tests with 1 client and hatch 1, and looked on my application log and counted the request. The locust WebUI showed me that they were 26 requests made after I stoped the test, but in the /var/log/httpd/access_log I counted 31 requests ..so there is a difference by 5 requests which haven't been displayed neither in API nor WebUI.

**Comment by aldenpeterson-wf** [comment]
I have seen some requests happen while locust itself is initializing

**Comment by Microndgt** [comment]
![](http://7xq6lu.com1.z0.glb.clouddn.com/locust.png)

**Comment by heyman** [comment]
This might also happen if a request returns a HTTP redirect, since I believe the default behaviour for python requests is to follow redirects, and Locust will then group them both (all) together and record them under a single request entry.

It could definitely be argued that they should be recorded separately, but that would cause problem in cases where one is using the `name` argument to group together URLs that have some dynamic parts (e.g. an ID).
