### ISSUE TITLE
Slave count doesn't get updated in the UI if no more slaves are alive

### ISSUE THREAD

**Issue by bogdangherca** [locustio/locust#62]
Hi,

I was running some simple tests with locust (which is so cool btw) and I noticed that if you end up with no slaves connected, the UI does not reflect this change. The slave count in the UI sticks to 1 in this case.
Also, it would be nice to get a warning message in the webUI if you start swarming with no slaves connected. Now, you get this warning only in the command line.

I could provide a quick fix for this if you'd like.

Thanks!

**Comment by vorozhko** [comment]
Hello guys,
I has similar issue. Master and web UI doesn't reflect the actual slaves count.
We run locust in Docker containers. My setup include 200 slaves, so 200 docker containers.
Master has registered them all. But, when containers number was downscaled to 10, master and web UI still show 200 slaves assigned.

Our docker is using latest locustio package from pip.
Any advice is appreciated.

Thanks!

**Comment by jtpio** [comment]
@vorozhko:
I ran into the same issue with the following setup:
- locust master and slaves running in Docker containers
- Docker containers orchestrated with Kubernetes on 4 VMs (private cluster)

The problem is related to how the containers are stopped. For a locust slave to be properly terminated and the number correctly updated, it needs to send the `quit` message when handling the SIGTERM event by calling the [shutdown function](https://github.com/locustio/locust/blob/v0.8a1/locust/main.py#L436).

In my case, the entrypoint for the container is a shell script which starts locust as a **child process**. It means that the shell script will be assigned PID 1 and the locust script a different PID. When `docker stop` is called, it send the SIGTERM event to the process with PID 1. But if it is not handled, it waits 10s and then kill the container (and locust can't shutdown gracefully).

The locust start-up I'm using is mostly inspired by https://github.com/peter-evans/locust-docker. With that setup, the easy fix was to prepend `exec` to replace the shell with the python program, so locust gets PID 1 and can handle the SIGTERM signal:

`exec $LOCUST_PATH $LOCUST_FLAGS`

Another way to fix this problem would be to handle the case when a slave is disconnected in the locust code itself (socket closed or similar).
