### ISSUE TITLE
Add new members to Committers Team in the Locust.io Organization

### ISSUE THREAD

**Issue by cgoldberg** [locustio/locust#628]
I suggest we tweak the list of folks with push access to the Locust repo.

@heyman,
Could you invite the following 2 people to become Members of the Locust.io Organization and add them to the Committers Team? (https://github.com/orgs/locustio/teams/committers/members):

 * @aldenpeterson-wf (Alden Peterson)
 * @mbeacom (Mark Beacom)

Both Alden and Mark have been active with Locust and demonstrated they are responsible and willing to help maintain the Locust project.  This elevated access will give them the ability to merge PR's and close Issues (among other things), which would be a big help.

There are currently 10 people in the Locust.io Organization with push access to the Locust repo.  It's probably a good idea to audit the list of committers and remove anyone that is no longer active with the project

* Only @heyman or @cgbystrom can currently make changes to the Organization as they are the only 2 'Owners'.  If you elevate me to an organization Owner or change my role in the Committers Team to Maintainer, I will happily take care of the changes myself.

Thanks!

**Comment by aldenpeterson-wf** [comment]
Also, I'm not sure what is needed for releasing to pypy but it would be good to expand the list of people who can actually do that, even if only to get new RCs out.

**Comment by mbeacom** [comment]
I'm on board to help where I can! 
Thanks

**Comment by heyman** [comment]
Hi, sorry for the delay. I've been mostly AFK this whole summer. I've added both @aldenpeterson-wf  and @mbeacom as committers now. @cgoldberg is currently a maintainer for the PyPI package. Let me know if I should add someone else as well.

**Comment by aldenpeterson-wf** [comment]
Sounds good!

**Comment by mbeacom** [comment]
@heyman @cgbystrom  Would it be possible for @aldenpeterson-wf and myself to receive pypi publishing access?  We'd love to resolve the `0.8` pip installation issues and get the ball rolling on releases again.

Thank you!

**Comment by aldenpeterson-wf** [comment]
+1 it's been pretty frustrating trying to come on board and basically seeing that there's not a lot of involvement from anyone other than @mbeacom.

That's not necessarily a bad thing as long as people who _are_ active and involved can actually get stuff done and it'd be nice.

Selfishly I know a few of my PRs are getting a lot of drive-by love and it'd be great to get them into an RC at the very least so that we can verify the 0.8 package and let people play with it.

Right now, that entire process is hung though so more people with the ability and desire to be involved would be great 🎉

**Comment by cyberw** [comment]
Solved and then re-solved, now with new members and a suggested approach for automatically pushing to pypi!
