### ISSUE TITLE
 failure to install the latest version locust

### ISSUE THREAD

**Issue by michaelia** [locustio/locust#648]
### Description of issue / feature request
alway show the message ，but Cannot continue installation。
message：
initlibsodium.obj : warning LNK4197: export 'PyInit_libsodium' specified multiple times; using first specification
Creating library build\temp.win-amd64-3.6\Release\buildutils\libsodium.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\buildutils\libsodium.cp36-win_amd64.exp
Generating code

### Actual behavior
install 

### Environment settings (for bug reports)

- OS:window 10 
- Python version:3.6
- Locust version:0.8

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by heyman** [comment]
How do you install Locust? Using pip?

Is that the whole output that you get?

Is anyone else able to install the latest Locust version on Windows?

**Comment by heyman** [comment]
I just went through installing Locust on a pretty clean Windows 10 (Python 3.6) machine.

I *did* run into some problems that were caused by us pinning the pyzmq version. Therefore I "unpinned" it (and upgraded to the lastest stable pyzmq version) and issued a new release (0.8.1) on PyPI. I'm now able to install Locust on Windows by simply running `pip install locustio`.

However, I don't know if your issue is related @michaelia? It'd be great if you could give it another try! Also, I'm wondering pasted output is truncated? If so maybe you could post the whole output. Thanks!

**Comment by mbeacom** [comment]
Closing due to lack of response. @michaelia Please re-open this issue after upgrading to `0.8.1`, if necessary.
