### ISSUE TITLE
Allowing custom options to passed into tests?

### ISSUE THREAD

**Issue by amandasaurus** [locustio/locust#65]
I'm just starting using locust to test our application. Our application can have slugs in the URL that I want to test against. Rather than have to change the task file to put in a new slug to test, I hacked locust to have a `-o key value` (or `--option key value`) command line options that will be available in the task as `self.options[key]`. 

I've done some work on this branch: https://github.com/rory/locust/tree/custom-options  (see the diff here https://github.com/rory/locust/compare/master...custom-options ). I haven't requested a pull yet because I'm unsure if I'm doing it in a sensible way. I haven't tested this using the master/slave/distributed workflow, since we're not using that yet.

Can you tell me if this is a good feature others might want, and if I'm doing it in a good way?

**Comment by liaogz82** [comment]
Hi. I am running locustio to simulate many clients stressing a server. I need to be able to pass the GameDataVersion from command line so I do not have to keep edit the variable value on locustfile.py. It is for convenience sake

**Comment by crysyn** [comment]
The odd thing here is the TaskSet object accepts *args and *kwargs, sets them to self.args and self.kwargs but the calling Locust object does not pass anything into the .run() call.. It looks like this was intended functionality but just never implemented? This would be very handy in my test environment where I need to change the states of the running environment more definitively then is currently possible with Locust (I've already made a few classes to support this gracefully within the environment but as has been said and parroted by others, not having to rewrite a .py file every time I need to change a parameter to it would be very helpful)

**Comment by heyman** [comment]
@crysyn The args and kwargs are set when scheduling a nested TaskSet using `TaskSet.schedule_task()` (http://docs.locust.io/en/latest/api.html#locust.core.TaskSet.schedule_task).

Can't you set an environment variable when starting locust like this:

```
$ env MY_VAR=1 locust -f testfile.py [...]
```

and then read it in your test script like this

```python
import os

class MyTaskSet(TaskSet):
    def some_task(self):
        if os.environ.get("MY_VAR"):
            ...
```

You would still need to restart Locust, but at least you don't need to change the python code.

**Comment by markfickett** [comment]
I'm trying out Locust (very convenient so far!), and have run into this too. My use case is that our app requires a service account token from a file for authentication. I can/will use environment variables, but I like command-line arguments better just for code clarity; env vars tend to be hard to trace / easy to overwrite, since they're effectively globals.

**Comment by crysyn** [comment]
@markfickett This was a while ago for me but IIRC I ended up writing my own class objects that did what I wanted here so we could hook the tests into jenkins and such to get the appropriate values as well as improve iteration for people developing the scripts.

**Comment by DenerKup** [comment]
Env vars is the one of the worst workarounds, because you need to read code of the test to known which env vars you should pass. Arguments for a script with adequate help messages and stuff like `default` and `required` will be useful. I think that options parsing should be moved to argparse and some on_setup interface should be exposed to populate parser with additional own parameters.

Or there will be a problems with distributed version in such case? Anyway env vars doesn't look better at such situation.

**Comment by aldenpeterson-wf** [comment]
@DenerKup we've talked about using yaml config that python reads.

**Comment by stixaw** [comment]
can't we use a json config?  I hate YAML

Is this available
I have 2 different environments and a JWT Token that uses different secrets and ids that i would love to do -e dev and have it read the  necessary variables from a config or utility python script.

**Comment by aldenpeterson-wf** [comment]
> is there a support thread or group for getting help with LocustIo stuff?

@stixaw check out the Slack link on the readme :) https://github.com/locustio/locust
