### ISSUE TITLE
Release new Locust version

### ISSUE THREAD

**Issue by heyman** [locustio/locust#657]
I think it's time we do a real release of 0.8 so that people can actually get the latest version (with Python 3 support) when they run `pip install locustio`.

I'd like to get #656 and #549 merged as soon as possible and I propose that we do one of the following three things:

1. Merge both #656 and #549 and then release 0.8 (YOLO)
2. Merge both #656 and #549, release a 0.8rc5, wait a week, and then release 0.8.
3. Release the current master as 0.8, then merge #656 and #549 and immediately release a 0.9rc1.

What do you think?

ping @cgoldberg @aldenpeterson-wf @justiniso @mbeacom @pmdarrow

**Comment by aldenpeterson-wf** [comment]
I'd be in favor of releasing current master as 0.8 now and building a RC for those other PRs.

Mainly because #656 will potentially be a big change for how people are using Locust with `--no-web` and it'd be nice to put that into another RC (there were a lot of changes in 0.8 too).

Plus, not really a big deal to have lots of releases in my opinion. I'm almost always a fan of more releases vs larger ones when digital space is involved, too, makes it easier to identify any regressions :)

**Comment by heyman** [comment]
Ok, that sounds good to me! I'll go ahead and make a release of 0.8 now then.

**Comment by heyman** [comment]
0.8 has been released!
