### ISSUE TITLE
500 URL limit

### ISSUE THREAD

**Issue by gda2004** [locustio/locust#786]
### Feature request
Would it be possible to make the number of URL's that can be hit, configurable?

**Comment by cgoldberg** [comment]
can you provide some context?  do you mean the URL's reported in the UI?

**Comment by gda2004** [comment]
yes the charts seem to stop working correctly when we hit 500. I believe the issue maybe in web.py ?

**Comment by cgoldberg** [comment]
looks like it gets truncated at 500 in web.py... the UI rendered extremely slowly with too many rows.

To make this configurable, we first need to add support for using a config/settings file (which Locust currently lacks).

**Comment by cyberw** [comment]
I think >500 different requests is rarely useful, and wouldnt really scale anyway.

If the problem is that your URLs are very dynamic, use the name parameter to make them get the same name, see https://docs.locust.io/en/stable/writing-a-locustfile.html#grouping-requests-to-urls-with-dynamic-parameters
