### ISSUE TITLE
How to understand -c when I run locust with no-web mode?

### ISSUE THREAD

**Issue by qushengswaych** [locustio/locust#965]
### Description of issue / feature request
When I run locust with no-web mode, there's a opt -c.The description of it is the number of concurrent Locust users.So when I run locust with command "locust -t 30s -c 80 -r 80 --no-web -f xx.py", what's the difference between running locust with "-c 100 -r100".I get the similar req/s and the tp75 and tp99 always increase 150ms or more.

### Expected behavior

TBD

### Actual behavior

TBD

### Environment settings (for bug reports)

- OS:Mac OS
- Python verson:2.7.10
- Locust version:0.9.0

### Steps to reproduce (for bug reports)

TBD - [example code appreciated](https://stackoverflow.com/help/mcve)

**Comment by cgoldberg** [comment]
well..

`-c 80 -r 80` will spawn 80 clients (users) at a rate of 80 per second.  So, 1 second into your test, all 80 clients would be hatched and running.

`-c 100 -r 100` will spawn 100 clients (users) at a rate of 100 per second.  So 1 second into your test, all 100 clients would be hatched. and running.

As you can see... keeping `-c` and `-r` set to the same number isn't a very good use of hatch rate, since the hatch period will only last second.

**Comment by cgoldberg** [comment]
closing, since there is no bug/issue reported here.

**Comment by qushengswaych** [comment]
I got less requests and lower req/s when using -c 50 -r 10 than using-c 100 -r 10.So did this mean I use  it in a wrong way?
